const MAX_ROUND = 140;
const TICKS_PER_ROUND = 1260;
const PATH_KEYS = ["top", "middle", "bottom"];
const PATH_INDEX = { top: 0, middle: 1, bottom: 2 };
const PATH_LABELS = { top: "Top", middle: "Middle", bottom: "Bottom" };

const state = {
  settings: {
    mode: "Timed", goal: "money", targetCashByRound: "", roundStart: 1, startingCash: 650,
    mapDifficulty: "Beginner", players: 1, monkeyKnowledge: true, selectedHero: "quincy",
    maxTowers: 999, maxBananaFarms: 999, maxBoatSpots: 0, lordOfAbyss: 0,
    coverage: { villageBaseFarm: 5, village100Farm: 6, village104Farm: 8, boat: 0 }
  },
  endRound: 40,
  events: [],
  monkeyInstances: {},
  buffs: [],
  paragonHistory: {},
  selectedEventId: null,
  selectedCumulative: null,
  inspectorTab: "action",
  nextEventNumber: 1,
  nextMonkeyNumber: 1,
  nextBuffNumber: 1,
  nextParagonNumber: 1,
  tutorialIndex: 0
};

const el = {
  targetCashSubsection: document.getElementById("targetCashSubsection"), targetCashByRound: document.getElementById("targetCashByRound"),
  roundStart: document.getElementById("roundStart"), startingCash: document.getElementById("startingCash"), mapDifficulty: document.getElementById("mapDifficulty"), players: document.getElementById("players"),
  monkeyKnowledge: document.getElementById("monkeyKnowledge"), selectedHero: document.getElementById("selectedHero"), maxTowers: document.getElementById("maxTowers"), maxBananaFarms: document.getElementById("maxBananaFarms"), maxBoatSpots: document.getElementById("maxBoatSpots"), lordOfAbyss: document.getElementById("lordOfAbyss"),
  villageBaseFarmCoverage: document.getElementById("villageBaseFarmCoverage"), village100FarmCoverage: document.getElementById("village100FarmCoverage"), village104FarmCoverage: document.getElementById("village104FarmCoverage"), boatCoverage: document.getElementById("boatCoverage"),
  endRoundInput: document.getElementById("endRoundInput"), buildRoundsButton: document.getElementById("buildRoundsButton"), calculateButton: document.getElementById("calculateButton"),
  roundTableBody: document.getElementById("roundTableBody"), cumulativeList: document.getElementById("cumulativeList"), availableTowerList: document.getElementById("availableTowerList"), geraldoShelf: document.getElementById("geraldoShelf"), existingTowerList: document.getElementById("existingTowerList"), availabilityList: document.getElementById("availabilityList"), inspectorContent: document.getElementById("inspectorContent"), clearSelectionButton: document.getElementById("clearSelectionButton"), toast: document.getElementById("toast"),
  tutorialOverlay: document.getElementById("tutorialOverlay"), tutorialTitle: document.getElementById("tutorialTitle"), tutorialText: document.getElementById("tutorialText"), tutorialSkip: document.getElementById("tutorialSkip"), tutorialNext: document.getElementById("tutorialNext")
};

function init(){ hydrateIcons(); populateHeroes(); bindGlobalControls(); bindTabs(); updateMonkeyKnowledgeIcon(); renderAll(); startTutorial(); }
function hydrateIcons(root=document){ root.querySelectorAll("[data-icon-key]").forEach(slot=>slot.innerHTML=iconHtml(slot.dataset.iconKey)); }
function iconHtml(key){ const e=window.BTD6_IMAGES?.[key]; if(!e) return `<span class="icon-fallback">❔</span>`; if(e.src) return `<img class="icon-img" src="${e.src}" alt="${key}" draggable="false" onerror="this.replaceWith(Object.assign(document.createElement('span'),{className:'icon-fallback',textContent:'${e.fallback||"●"}'}))">`; return `<span class="icon-fallback">${e.fallback||"●"}</span>`; }
function populateHeroes(){ el.selectedHero.innerHTML = window.BTD6_HEROES.map(h=>`<option value="${h.id}">${h.name}</option>`).join(""); el.selectedHero.value = state.settings.selectedHero; }

function bindGlobalControls(){
  document.querySelectorAll(".segment-option").forEach(button=>button.addEventListener("click",()=>{ const setting=button.dataset.setting, value=button.dataset.value; button.parentElement.querySelectorAll(".segment-option").forEach(o=>o.classList.remove("active")); button.classList.add("active"); state.settings[setting]=value; updateConditionalControls(); }));
  bindSettingInput(el.targetCashByRound,"targetCashByRound","string"); bindSettingInput(el.startingCash,"startingCash","number"); bindSettingInput(el.mapDifficulty,"mapDifficulty","string"); bindSettingInput(el.players,"players","number",()=>{ state.settings.players=clamp(state.settings.players,1,4); el.players.value=state.settings.players; sanitizePlanForRules(); }); bindSettingInput(el.maxTowers,"maxTowers","number",renderAll); bindSettingInput(el.maxBananaFarms,"maxBananaFarms","number",renderAll); bindSettingInput(el.maxBoatSpots,"maxBoatSpots","number",()=>{ state.settings.maxBoatSpots=Math.max(0,state.settings.maxBoatSpots); el.maxBoatSpots.value=state.settings.maxBoatSpots; renderAll(); });
  el.roundStart.addEventListener("change",()=>{ state.settings.roundStart=clamp(Number(el.roundStart.value||1),1,MAX_ROUND); el.roundStart.value=state.settings.roundStart; removeEventsBeforeRoundStart(); renderAll(); });
  el.monkeyKnowledge.addEventListener("change",()=>{ state.settings.monkeyKnowledge=el.monkeyKnowledge.checked; updateMonkeyKnowledgeIcon(); sanitizePlanForRules(); renderAll(); });
  el.lordOfAbyss.addEventListener("input",()=>{ state.settings.lordOfAbyss=Math.max(0,Number(el.lordOfAbyss.value||0)); el.lordOfAbyss.value=state.settings.lordOfAbyss; renderAll(); });
  el.selectedHero.addEventListener("change",()=>{ state.settings.selectedHero=el.selectedHero.value; sanitizeHeroesForSelection(); sanitizePlanForRules(); renderAll(); });
  el.villageBaseFarmCoverage.addEventListener("input",()=>state.settings.coverage.villageBaseFarm=Number(el.villageBaseFarmCoverage.value||0));
  el.village100FarmCoverage.addEventListener("input",()=>state.settings.coverage.village100Farm=Number(el.village100FarmCoverage.value||0));
  el.village104FarmCoverage.addEventListener("input",()=>state.settings.coverage.village104Farm=Number(el.village104FarmCoverage.value||0));
  el.boatCoverage.addEventListener("input",()=>state.settings.coverage.boat=Number(el.boatCoverage.value||0));
  el.endRoundInput.addEventListener("input",()=>{ state.endRound=clamp(Number(el.endRoundInput.value||1),1,MAX_ROUND); el.endRoundInput.value=state.endRound; });
  el.buildRoundsButton.addEventListener("click",()=>{ state.endRound=clamp(Number(el.endRoundInput.value||1),1,MAX_ROUND); el.endRoundInput.value=state.endRound; renderAll(); });
  el.calculateButton.addEventListener("click",runCalculator);
  el.clearSelectionButton.addEventListener("click",()=>{ state.selectedEventId=null; state.selectedCumulative=null; renderInspector(); renderRoundTable(); renderCumulative(); });
  document.querySelectorAll("[data-inspector-tab]").forEach(button=>button.addEventListener("click",()=>{ state.inspectorTab=button.dataset.inspectorTab; document.querySelectorAll("[data-inspector-tab]").forEach(o=>o.classList.toggle("active",o.dataset.inspectorTab===state.inspectorTab)); renderInspector(); }));
  el.tutorialSkip.addEventListener("click",endTutorial); el.tutorialNext.addEventListener("click",nextTutorialStep);
}
function bindSettingInput(element,key,type,after){ element.addEventListener("input",()=>{ state.settings[key]=type==="number"?Number(element.value||0):element.value; if(after) after(); renderRoundTable(); renderCumulative(); }); }
function updateMonkeyKnowledgeIcon(){ const icon=el.monkeyKnowledge?.closest(".toggle-row")?.querySelector("[data-icon-key]"); if(!icon)return; icon.dataset.iconKey=state.settings.monkeyKnowledge?"mk":"mkOff"; icon.innerHTML=iconHtml(icon.dataset.iconKey); }
function bindTabs(){ document.querySelectorAll("[data-center-tab]").forEach(b=>b.addEventListener("click",()=>setTab("center",b.dataset.centerTab))); document.querySelectorAll("[data-right-tab]").forEach(b=>b.addEventListener("click",()=>setTab("right",b.dataset.rightTab))); }
function setTab(side,tab){ const buttonSelector=side==="center"?"[data-center-tab]":"[data-right-tab]"; const ids=side==="center"?["editorTab","cumulativeTab"]:["availableTab","existingTab","availabilityTab"]; document.querySelectorAll(buttonSelector).forEach(b=>b.classList.toggle("active",(side==="center"?b.dataset.centerTab:b.dataset.rightTab)===tab)); ids.forEach(id=>document.getElementById(id).classList.toggle("active",id===`${tab}Tab`)); if(tab==="cumulative")renderCumulative(); if(tab==="existing")renderExistingTowers(); }
function updateConditionalControls(){ const show=state.settings.mode==="Least Cash"||state.settings.mode==="Least Tiers"; el.targetCashSubsection.classList.toggle("hidden",!show); }
function renderAll(){ updateConditionalControls(); renderAvailableTowers(); renderExistingTowers(); renderAvailabilityRules(); renderRoundTable(); renderCumulative(); renderInspector(); }

function renderAvailableTowers(){
  el.availableTowerList.innerHTML="";
  el.availableTowerList.appendChild(availableCard({type:"helper-pop-income", id:"pop-income", iconKey:"popIncome", priceLabel:"Pop", category:"helper"}));
  const hero=getSelectedHero(); if(hero && hero.id!=="none" && !hasHeroPlaced(hero.id)) el.availableTowerList.appendChild(availableCard({type:"hero", id:hero.id, iconKey:hero.iconKey, price:hero.baseCost||0, title:hero.name, category:"hero"}));
  window.BTD6_TOWERS.forEach(t=>{ const disabled=!t.enabled||!hasAnyAvailablePath(t)||wouldBreakTowerLimits(t.id); el.availableTowerList.appendChild(availableCard({type:"tower",id:t.id,iconKey:t.iconKey,price:t.baseCost,title:t.name,disabled,category:t.category})); });
  renderGeraldoShelf();
}
function availableCard(data){ const card=document.createElement("div"); card.className=`available-tower ${categoryClass(data.category)} ${data.disabled?"disabled":""}`; card.draggable=!data.disabled; card.title=data.title||data.id; card.innerHTML=`<div class="available-icon">${iconHtml(data.iconKey)}</div><div class="available-price">${data.priceLabel||formatMoney(data.price||0)}</div>`; card.addEventListener("dragstart",ev=>{ if(data.disabled){ev.preventDefault();return;} ev.dataTransfer.setData("text/plain",JSON.stringify({type:data.type,id:data.id})); }); return card; }
function renderGeraldoShelf(){ el.geraldoShelf.innerHTML=""; if(state.settings.selectedHero!=="geraldo")return; el.geraldoShelf.innerHTML=`<details open><summary>Geraldo Goodies</summary><div class="geraldo-items" id="geraldoItems"></div></details>`; const list=document.getElementById("geraldoItems"); window.BTD6_GERALDO_ITEMS.forEach(item=>list.appendChild(availableCard({type:"geraldo-item",id:item.id,iconKey:item.iconKey,price:item.cost,title:item.name,category:"hero"}))); }

function renderExistingTowers(){
  el.existingTowerList.innerHTML=""; const instances=Object.values(state.monkeyInstances).sort((a,b)=>a.label.localeCompare(b.label));
  if(!instances.length){el.existingTowerList.innerHTML=`<div class="empty-inspector">No existing monkeys yet.</div>`;return;}
  instances.forEach(inst=>{ const meta=getInstanceMeta(inst); const current=getMonkeyStateAtRound(inst.id,state.endRound); const absorbedBlocked=isExistingDragDisabled(inst,state.endRound); const sold=current.sold; const card=document.createElement("div"); card.className=`existing-card ${categoryClass(meta.category)} ${sold?"sold":""} ${absorbedBlocked?"disabled":""} ${meta.absorbedVisible?"absorbed":""}`; card.draggable=true; card.innerHTML=`<div class="card-title">${iconHtml(meta.iconKey)}<span>${inst.label}</span></div><div class="card-meta">${meta.typeLabel} · ${sold?"Sold":current.upgrade||"No paths"}${meta.absorbedText?` · ${meta.absorbedText}`:""}</div>`; card.addEventListener("click",()=>window.selectCumulative(inst.id,state.endRound)); card.addEventListener("dragstart",ev=>{ ev.dataTransfer.setData("text/plain",JSON.stringify({type:"existing-monkey",monkeyId:inst.id})); }); el.existingTowerList.appendChild(card); });
}
function renderAvailabilityRules(){ el.availabilityList.innerHTML=""; window.BTD6_TOWERS.forEach(t=>{ const card=document.createElement("div"); card.className="availability-card"; card.innerHTML=`<div class="availability-icon">${iconHtml(t.iconKey)}</div><div><div class="availability-name-row"><span>${t.name}</span><label class="mini-check"><input type="checkbox" data-rule="tower" data-tower-id="${t.id}" ${t.enabled?"checked":""}>Enabled</label></div><div class="tier-stack">${tierControlHtml("availability",t.id,"top",t.maxPathTiers.top,false)}${tierControlHtml("availability",t.id,"middle",t.maxPathTiers.middle,false)}${tierControlHtml("availability",t.id,"bottom",t.maxPathTiers.bottom,false)}</div></div>`; card.querySelector("[data-rule='tower']").addEventListener("change",ev=>{ getTower(ev.target.dataset.towerId).enabled=ev.target.checked; sanitizePlanForRules(); renderAll(); }); el.availabilityList.appendChild(card); }); }
function tierControlHtml(kind,id,path,value,showParagon=false,paragonReady=false,paragonActive=false){ return `<div class="tier-control ${showParagon?"":"no-paragon"}"><span class="tier-label">${PATH_LABELS[path]}</span><button class="step-btn" onclick="changeTierValue('${kind}','${id}','${path}',-1)">−</button><span class="tier-value">${value}</span><button class="step-btn" onclick="changeTierValue('${kind}','${id}','${path}',1)">+</button>${showParagon?`<button class="paragon-btn ${paragonReady?"ready":""} ${paragonActive?"active":""}" ${paragonReady?"":"disabled"} onclick="createParagonFromSelected('${id}')">${iconHtml("paragon")}</button>`:""}</div>`; }
window.changeTierValue=function(kind,id,path,delta){ if(kind==="availability"){ const t=getTower(id); t.maxPathTiers[path]=clamp(t.maxPathTiers[path]+delta,0,5); sanitizePlanForRules(); renderAll(); return; } if(kind==="selected"){ const ev=state.events.find(e=>e.id===id); if(!ev||ev.type!=="upgrade")return; const t=getTower(ev.towerId); const next=changeUpgradeTier(ev.upgrade,path,delta); if(!next||!isUpgradePatternAllowed(next,t)){showToast("That upgrade breaks path/rule limits.");return;} ev.upgrade=next; ev.dirty=true; sanitizePlanForRules(); renderAll(); } };

function renderRoundTable(){ const rows=calculateRows(); el.roundTableBody.innerHTML=""; for(let r=state.settings.roundStart;r<=state.endRound;r++){ const row=rows.find(x=>x.round===r); if(!row)continue; const tr=document.createElement("tr"); tr.className=`round-row ${row.conflict?"conflict":"ok"}`; tr.dataset.round=r; tr.innerHTML=`<td><strong>${r}</strong></td><td class="money-cell">${formatMoney(row.startMoney)}</td><td class="money-cell">${formatMoney(row.popIncome)}</td><td class="money-cell">${formatMoney(row.endIncome)}</td><td class="money-cell">${formatMoney(row.endMoney)}</td><td><div class="round-actions">${renderEventChipsForRound(r)}</div></td>`; bindDropHandlers(tr,r); el.roundTableBody.appendChild(tr); } }
function renderEventChipsForRound(round){ const events=state.events.filter(e=>e.round===round).sort(compareEvents); if(!events.length)return `<span class="empty-drop-zone">Drop action here</span>`; return events.map(eventChipHtml).join(""); }
function eventChipHtml(ev){ const m=ev.monkeyId?state.monkeyInstances[ev.monkeyId]:null; const meta=m?getInstanceMeta(m):getHelperMeta(ev); const selected=state.selectedEventId===ev.id?"selected":""; const classes=["action-chip",categoryClass(meta.category),selected,ev.source==="generated"?"generated":"",ev.dirty?"dirty":"",ev.type==="sell"?"sell":"",isSpecialEvent(ev)?"special":"",meta.absorbedVisible?"absorbed":""].filter(Boolean).join(" "); const price=eventPriceLabel(ev); return `<button class="${classes}" draggable="true" ondragstart="dragEventChip(event,'${ev.id}')" onclick="selectEvent('${ev.id}')">${iconHtml(meta.iconKey)}<span class="chip-title">${eventLabel(ev,m)}</span>${price?`<span class="chip-price">${price}</span>`:""}<span class="tick-badge">@${ev.tick}</span></button>`; }
function eventLabel(ev,m){ if(ev.type==="place")return `Place ${m.label}`; if(ev.type==="place-hero")return `Place ${m.label}`; if(ev.type==="place-geraldo-item")return `Buy ${m.label}`; if(ev.type==="upgrade")return `${m.label} → <span class="upgrade-code">${ev.upgrade}</span>`; if(ev.type==="hero-level")return `Skip ${m.label} Levels`; if(ev.type==="sell")return `Sell ${m.label}`; if(ev.type==="bank-collect")return `Collect ${m.label} Bank`; if(ev.type==="bank-deposit")return `Deposit ${m.label} Bank`; if(ev.type==="absorb")return `Absorb into ${m.label}`; if(ev.type==="paragon")return `Create ${m.label}`; if(ev.type==="ability")return `Use ${m.label} Ability`; if(ev.type==="pop-income")return `Pop Income ${formatMoney(ev.amount||0)}`; return ev.type; }
function eventPriceLabel(ev){ const delta=getMoneyDelta(ev,ev.round); if(ev.type==="sell")return ""; if(ev.type==="pop-income")return formatMoney(delta); if(delta<0)return formatMoney(Math.abs(delta)); if(delta>0)return formatMoney(delta); return ""; }
function categoryClass(category){ return `cat-${String(category||"helper").toLowerCase().replace(/[^a-z0-9]+/g,"-")}`; }
function bindDropHandlers(row,round){ row.addEventListener("dragover",ev=>{ev.preventDefault();row.classList.add("drop-hover")}); row.addEventListener("dragleave",()=>row.classList.remove("drop-hover")); row.addEventListener("drop",ev=>{ev.preventDefault();row.classList.remove("drop-hover"); const raw=ev.dataTransfer.getData("text/plain"); if(!raw)return; const p=JSON.parse(raw); if(p.type==="tower")placeNewTower(p.id,round,"manual"); if(p.type==="hero")placeHero(p.id,round); if(p.type==="geraldo-item")placeGeraldoItem(p.id,round); if(p.type==="helper-pop-income")addPopIncomeAction(round); if(p.type==="existing-monkey")handleExistingDrop(p.monkeyId,round); if(p.type==="event-action")moveEventToRound(p.eventId,round); }); }

window.dragEventChip=function(ev,eventId){ ev.dataTransfer.setData("text/plain",JSON.stringify({type:"event-action",eventId})); ev.dataTransfer.effectAllowed="move"; };
function moveEventToRound(eventId,round){ const ev=state.events.find(e=>e.id===eventId); if(!ev)return; ev.round=clamp(Number(round||state.settings.roundStart),state.settings.roundStart,MAX_ROUND); ev.dirty=true; state.selectedEventId=ev.id; renderAll(); }

function placeNewTower(towerId,round,source="manual"){ const t=getTower(towerId); if(!t.enabled||!hasAnyAvailablePath(t)){showToast("Tower disabled by rules.");return null;} if(wouldBreakTowerLimits(towerId)){showToast("Tower limit would be exceeded.");return null;} const id=makeId("monkey",state.nextMonkeyNumber++); const label=`${t.shortName||t.name} #${countExistingTower(towerId)+1}`; state.monkeyInstances[id]={id,towerId,label,kind:"tower"}; const ev=makeEvent({monkeyId:id,towerId,round,type:"place",upgrade:"000",source}); state.events.push(ev); renderAll(); return id; }
function placeHero(heroId,round){ const h=getHero(heroId); if(hasHeroPlaced(heroId)){showToast("That hero is already placed.");return;} const id=makeId("monkey",state.nextMonkeyNumber++); state.monkeyInstances[id]={id,heroId,label:h.name,kind:"hero"}; state.events.push(makeEvent({monkeyId:id,heroId,round,type:"place-hero",source:"manual"})); renderAll(); }
function placeGeraldoItem(itemId,round){ const item=getGeraldoItem(itemId); const id=makeId("monkey",state.nextMonkeyNumber++); state.monkeyInstances[id]={id,itemId,label:item.name,kind:"geraldo-item"}; state.events.push(makeEvent({monkeyId:id,itemId,round,type:"place-geraldo-item",source:"manual"})); renderAll(); }
function addPopIncomeAction(round){ state.events.push(makeEvent({round,type:"pop-income",amount:0,source:"manual"})); renderAll(); }
function handleExistingDrop(monkeyId,round){ const inst=state.monkeyInstances[monkeyId]; if(!inst)return; if(inst.kind==="hero"){ addHeroLevelAction(monkeyId,round); return; } if(inst.kind!=="tower"){ showToast("This object has no upgrade path."); return; } const t=getTower(inst.towerId); const current=getMonkeyStateAtRound(monkeyId,round); if(current.sold){showToast("This tower was sold before this point and cannot be added here.");return;} if(isExistingDragDisabled(inst,round)){showToast("This tower is absorbed at this point and cannot be dragged after the absorb.");return;} const next=getNextAvailableUpgrade(current.upgrade,t,monkeyId,round); if(!next){showToast("No legal next upgrade is available.");return;} state.events.push(makeEvent({monkeyId,towerId:inst.towerId,round,type:"upgrade",upgrade:next,source:"manual"})); sanitizePlanForRules(); renderAll(); }
function addHeroLevelAction(monkeyId,round){ state.events.push(makeEvent({monkeyId,heroId:state.monkeyInstances[monkeyId].heroId,round,type:"hero-level",moneySpent:0,source:"manual"})); renderAll(); }
function makeEvent(data){ return {id:makeId("event",state.nextEventNumber++),tick:0,sortOrder:Date.now()+Math.random(),dirty:false,...data}; }

function calculateRows(){ const rows=[]; let money=Number(state.settings.startingCash||0); for(let r=state.settings.roundStart;r<=state.endRound;r++){ let conflict=false; const startMoney=money; const popBase=Number(window.BTD6_ROUND_POP_INCOME?.[r]||0); const endIncome=getEndOfRoundIncome(r); const events=state.events.filter(e=>e.round===r).sort(compareEvents); let movedPop=0; for(const ev of events){ if(ev.type==="pop-income"){ const amount=clamp(Number(ev.amount||0),0,Math.max(0,popBase-movedPop)); ev.amount=amount; movedPop+=amount; } }
    for(const ev of events){ const delta=getMoneyDelta(ev,r); if(delta<0 && money+delta<0){ if(ev.tick===0){ conflict=true; } } if(delta<0 && money+delta<0){ conflict=true; } money += delta; if(money<0)conflict=true; }
    const remainingPop=Math.max(0,popBase-movedPop); money += remainingPop + endIncome; rows.push({round:r,startMoney,popIncome:popBase,endIncome,endMoney:money,conflict}); }
  return rows; }
function getMoneyDelta(ev,round){ if(ev.type==="place")return -Number(getTower(ev.towerId).baseCost||0); if(ev.type==="place-hero")return -Number(getHero(ev.heroId).baseCost||0); if(ev.type==="place-geraldo-item")return -Number(getGeraldoItem(ev.itemId).cost||0); if(ev.type==="upgrade")return -Number(getTower(ev.towerId).upgradeCosts?.[ev.upgrade]||0); if(ev.type==="sell")return calculateSellValue(ev.monkeyId,round); if(ev.type==="hero-level")return -Number(ev.moneySpent||0); if(ev.type==="bank-deposit")return -Number(ev.amount||0); if(ev.type==="bank-collect")return Number(ev.amount||0); if(ev.type==="pop-income")return Number(ev.amount||0); if(ev.type==="paragon")return -Number(ev.cost||0); return 0; }
function getEndOfRoundIncome(round){ return 100 + round + calculateEndRoundTowerIncome(round); }
function calculateEndRoundTowerIncome(round){ return 0; }

function renderCumulative(){ el.cumulativeList.innerHTML=""; for(let r=state.settings.roundStart;r<=state.endRound;r++){ const alive=Object.values(state.monkeyInstances).map(inst=>{const cur=getMonkeyStateAtRound(inst.id,r); if(!cur.placed||cur.sold)return null; const meta=getInstanceMeta(inst,r); return {inst,cur,meta};}).filter(Boolean); const card=document.createElement("div"); card.className="cumulative-round"; card.innerHTML=`<h3>Round ${r}</h3><div class="cumulative-pill-list">${alive.length?alive.map(x=>`<button class="action-chip generated ${x.meta.absorbedVisible?"absorbed":""}" onclick="selectCumulative('${x.inst.id}',${r})">${iconHtml(x.meta.iconKey)}<span>${x.inst.label}</span>${x.cur.upgrade?`<span class="upgrade-code">${x.cur.upgrade}</span>`:""}</button>`).join(""):`<span class="empty-inspector">No towers exist yet.</span>`}</div>`; el.cumulativeList.appendChild(card); } }
window.selectCumulative=function(monkeyId,round){ state.selectedEventId=null; state.selectedCumulative={monkeyId,round}; renderInspector(); renderCumulative(); renderRoundTable(); };
window.selectEvent=function(eventId){ state.selectedEventId=eventId; state.selectedCumulative=null; renderInspector(); renderRoundTable(); renderCumulative(); };

function renderInspector(){ const ev=state.events.find(e=>e.id===state.selectedEventId); if(state.selectedCumulative){renderCumulativeInspector();return;} if(!ev){el.inspectorContent.className="empty-inspector";el.inspectorContent.innerHTML="Click an action in the Round Map or a tower in Cumulative View.";return;} if(state.inspectorTab==="special")return renderSpecialInspector(ev); if(state.inspectorTab==="buffs")return renderBuffInspector(ev); return renderActionInspector(ev); }
function renderActionInspector(ev){ const inst=ev.monkeyId?state.monkeyInstances[ev.monkeyId]:null; const meta=inst?getInstanceMeta(inst):getHelperMeta(ev); el.inspectorContent.className="inspector-grid"; const isEditableUpgrade=ev.type==="upgrade"; const sellPointActive=!!(inst && state.events.some(e=>e.type==="sell"&&e.monkeyId===inst.id&&e.round===ev.round&&e.id!==ev.id)); const canParagon=isEditableUpgrade && !sellPointActive && getTower(ev.towerId)?.paragonAvailable; const paragonReady=canParagon && allT5sExistBefore(ev.towerId,ev.round); const upgradeEditor=isEditableUpgrade?`<div class="tier-stack ${sellPointActive?"disabled-stack":""}">${tierControlHtml("selected",ev.id,"top",Number(ev.upgrade[0]),canParagon,paragonReady,false)}${tierControlHtml("selected",ev.id,"middle",Number(ev.upgrade[1]),canParagon,paragonReady,false)}${tierControlHtml("selected",ev.id,"bottom",Number(ev.upgrade[2]),canParagon,paragonReady,false)}</div>`:``; const sellButton=inst?sellButtonHtml(ev,inst,sellPointActive):""; el.inspectorContent.innerHTML=`<div class="inspector-title">${iconHtml(meta.iconKey)}${inst?inst.label:eventLabel(ev,null)}</div><div class="card-meta">${ev.type.toUpperCase()} · Round ${ev.round} · ${ev.source==="generated"?"Generated":"Manual"}${ev.dirty?" · Edited":""}</div>${tickEditorHtml(ev)}<div class="stat-grid"><div class="stat-box"><div class="stat-label">Current Value</div><div class="stat-value">${inst?formatMoney(calculateTotalSpentOnMonkeyUntilRound(inst.id,ev.round)):"—"}</div></div><div class="stat-box"><div class="stat-label">Profit</div><div class="stat-value">${formatMoney(0)}</div></div><div class="stat-box"><div class="stat-label">Sell Value</div><div class="stat-value">${inst?formatMoney(calculateSellValue(inst.id,ev.round)):"—"}</div></div><div class="stat-box"><div class="stat-label">Action Delta</div><div class="stat-value">${formatMoney(getMoneyDelta(ev,ev.round))}</div></div></div>${sellPointActive?`<div class="sell-toggle-note">Sell mode is on here, so path interactions are dimmed for this action.</div>`:""}${upgradeEditor}${eventSpecificEditor(ev)}<div class="inspector-actions"><button class="danger" onclick="deleteSelectedEvent()">Delete Action</button>${sellButton}</div>`; bindTickEditor(ev); }
function sellButtonHtml(ev,inst,sellPointActive){ const stateAtEvent=getMonkeyStateAtRound(inst.id,ev.round); const isBasePlacement=["place","place-hero","place-geraldo-item"].includes(ev.type) || (ev.type==="upgrade"&&ev.upgrade==="000"); const isSell=ev.type==="sell"; const disabled=!isSell&&!sellPointActive&&(isBasePlacement||!stateAtEvent.placed||stateAtEvent.sold); const reason=isBasePlacement?"Sell is unavailable on the 000/base placement.":"Sell is unavailable here."; return `<button class="good ${sellPointActive||isSell?"active":""}" ${disabled?`disabled title="${reason}"`:""} onclick="toggleSellHereFromSelected()">${isSell?"Remove Sell Action":sellPointActive?"Undo Sell Here":"Sell Here"}</button>`; }
function tickEditorHtml(ev){ return `<div class="tick-editor"><div class="card-meta"><strong>Action Tick</strong></div><div class="tick-row"><input id="tickSlider" type="range" min="0" max="${TICKS_PER_ROUND}" value="${ev.tick}"><input id="tickText" type="number" min="0" max="${TICKS_PER_ROUND}" value="${ev.tick}"></div></div>`; }
function bindTickEditor(ev){ const s=document.getElementById("tickSlider"), t=document.getElementById("tickText"); if(!s||!t)return; const update=v=>{ ev.tick=clamp(Number(v||0),0,TICKS_PER_ROUND); ev.dirty=true; s.value=ev.tick; t.value=ev.tick; renderRoundTable(); renderCumulative(); }; s.addEventListener("input",()=>update(s.value)); t.addEventListener("change",()=>update(t.value)); }
function eventSpecificEditor(ev){ if(ev.type==="pop-income")return `<div class="mini-form"><label class="input-label">Pop income amount moved to this tick<input id="popAmountInput" type="number" min="0" value="${ev.amount||0}"></label></div>`; if(ev.type==="hero-level")return `<div class="mini-form"><label class="input-label">Money spent to skip levels<input id="heroSpendInput" type="number" min="0" value="${ev.moneySpent||0}"></label></div>`; if(ev.type==="bank-collect"||ev.type==="bank-deposit")return `<div class="mini-form"><label class="input-label">Amount<input id="bankAmountInput" type="number" min="0" value="${ev.amount||0}"></label></div>`; return ""; }
function wireEventSpecificEditor(ev){ const pop=document.getElementById("popAmountInput"); if(pop)pop.addEventListener("input",()=>{ev.amount=Number(pop.value||0);ev.dirty=true;renderRoundTable();}); const hero=document.getElementById("heroSpendInput"); if(hero)hero.addEventListener("input",()=>{ev.moneySpent=Number(hero.value||0);ev.dirty=true;renderRoundTable();}); const bank=document.getElementById("bankAmountInput"); if(bank)bank.addEventListener("input",()=>{ev.amount=Number(bank.value||0);ev.dirty=true;renderRoundTable();}); }
const oldRenderActionInspector=renderActionInspector; renderActionInspector=function(ev){ oldRenderActionInspector(ev); wireEventSpecificEditor(ev); };
function renderCumulativeInspector(){ const {monkeyId,round}=state.selectedCumulative; const inst=state.monkeyInstances[monkeyId]; if(!inst){state.selectedCumulative=null;renderInspector();return;} const meta=getInstanceMeta(inst,round); const cur=getMonkeyStateAtRound(monkeyId,round); el.inspectorContent.className="inspector-grid"; el.inspectorContent.innerHTML=`<div class="inspector-title">${iconHtml(meta.iconKey)}${inst.label}</div><div class="card-meta">Read-only cumulative view · Round ${round}</div><div class="stat-grid"><div class="stat-box"><div class="stat-label">Upgrade</div><div class="stat-value">${cur.upgrade||"—"}</div></div><div class="stat-box"><div class="stat-label">Status</div><div class="stat-value">${cur.sold?"Sold":"Alive"}</div></div><div class="stat-box"><div class="stat-label">Current Value</div><div class="stat-value">${formatMoney(calculateTotalSpentOnMonkeyUntilRound(monkeyId,round))}</div></div><div class="stat-box"><div class="stat-label">Sell Value</div><div class="stat-value">${formatMoney(calculateSellValue(monkeyId,round))}</div></div></div><div class="hint-box" style="margin:0;">Cumulative selections are visual only. To edit, select the action chip in the Round Map.</div>`; }

function renderSpecialInspector(ev){ const inst=ev.monkeyId?state.monkeyInstances[ev.monkeyId]:null; if(!inst){el.inspectorContent.className="empty-inspector"; el.inspectorContent.innerHTML="This action has no special menu."; return;} const cur=getMonkeyStateAtRound(inst.id,ev.round); const meta=getInstanceMeta(inst); let html=`<div class="inspector-grid"><div class="inspector-title">${iconHtml(meta.iconKey)}Special actions for ${inst.label}</div><div class="card-meta">Special menus create separate actions. They do not mutate the currently selected action.</div>`;
  if(inst.kind==="tower"){ const t=getTower(inst.towerId); if(isUpgradeAtLeast(cur.upgrade,t.specials?.bankCollectAt)) html+=`<div class="mini-form"><h2>Bank</h2><button onclick="addSpecialAction('${inst.id}','bank-collect')">Add Collect Action</button>${state.settings.monkeyKnowledge&&isUpgradeAtLeast(cur.upgrade,t.specials?.bankDepositAt)?`<button onclick="addSpecialAction('${inst.id}','bank-deposit')">Add Deposit Action</button>`:""}</div>`; if(isUpgradeAtLeast(cur.upgrade,t.specials?.absorbFarmsAt)) html+=absorbBoxHtml(inst,"farms","Farm Absorb Interface"); if(isUpgradeAtLeast(cur.upgrade,t.specials?.sunTempleAbsorbAt)||isUpgradeAtLeast(cur.upgrade,t.specials?.trueSunAbsorbAt)) html+=absorbBoxHtml(inst,"all","Sun Temple Absorb Interface"); if(t.abilities?.some(a=>isUpgradeAtLeast(cur.upgrade,a.minUpgrade))) html+=`<div class="mini-form"><h2>Abilities</h2>${t.abilities.filter(a=>isUpgradeAtLeast(cur.upgrade,a.minUpgrade)).map(a=>`<button onclick="addAbilityAction('${inst.id}','${a.id}')">${a.name}</button>`).join("")}</div>`; }
  if(inst.kind==="hero"){ const h=getHero(inst.heroId); html+=`<div class="mini-form"><h2>Hero Leveling</h2><button onclick="addSpecialAction('${inst.id}','hero-level')">Add Skip Level For Money Action</button></div>`; if(h.specials?.adoraAbsorb) html+=absorbBoxHtml(inst,"all","Adora Sacrifice / Absorb Interface"); }
  html+=`</div>`; el.inspectorContent.className="inspector-grid"; el.inspectorContent.innerHTML=html; bindAbsorbDropZones(inst,ev.round); }
function absorbBoxHtml(target,mode,title){ return `<div class="mini-form"><h2>${title}</h2><div class="drop-zone" data-absorb-target="${target.id}" data-absorb-mode="${mode}">Drag existing towers here to create a separate absorb action.</div><div class="card-meta">Absorbed towers get marked and are blocked after the absorb/paragon point.</div></div>`; }
function bindAbsorbDropZones(target,round){ document.querySelectorAll("[data-absorb-target]").forEach(zone=>{ zone.addEventListener("dragover",ev=>{ev.preventDefault();zone.classList.add("drop-hover")}); zone.addEventListener("dragleave",()=>zone.classList.remove("drop-hover")); zone.addEventListener("drop",ev=>{ev.preventDefault();zone.classList.remove("drop-hover"); const p=JSON.parse(ev.dataTransfer.getData("text/plain")||"{}"); if(p.type!=="existing-monkey"){showToast("Drop an existing monkey here.");return;} addAbsorbAction(target.id,p.monkeyId,round,zone.dataset.absorbMode); }); }); }
function renderBuffInspector(ev){ const inst=ev.monkeyId?state.monkeyInstances[ev.monkeyId]:null; if(!inst){el.inspectorContent.className="empty-inspector";el.inspectorContent.innerHTML="This action has no buff target.";return;} const buffs=getBuffsForMonkey(inst.id); el.inspectorContent.className="inspector-grid"; el.inspectorContent.innerHTML=`<div class="inspector-title">${iconHtml(getInstanceMeta(inst).iconKey)}Buffs for ${inst.label}</div><div class="drop-zone" id="buffDropZone">Drop existing monkey here as buff source</div><div class="buff-list">${buffs.length?buffs.map(buffCardHtml).join(""):`<div class="empty-inspector">No buffs assigned yet.</div>`}</div>`; bindBuffDropZone(inst.id); }
function buffCardHtml(buff){ const src=state.monkeyInstances[buff.sourceMonkeyId]; return `<div class="buff-card"><div class="card-title">${src?iconHtml(getInstanceMeta(src).iconKey):""}<span>${src?src.label:"Missing"}</span></div><div class="card-meta">Type: ${buff.type}</div><div class="inspector-actions"><button class="danger" onclick="removeBuff('${buff.id}')">Remove Buff</button></div></div>`; }
function bindBuffDropZone(targetMonkeyId){ const z=document.getElementById("buffDropZone"); if(!z)return; z.addEventListener("dragover",ev=>{ev.preventDefault();z.classList.add("drop-hover")}); z.addEventListener("dragleave",()=>z.classList.remove("drop-hover")); z.addEventListener("drop",ev=>{ev.preventDefault();z.classList.remove("drop-hover"); const p=JSON.parse(ev.dataTransfer.getData("text/plain")||"{}"); if(p.type!=="existing-monkey"){showToast("Drop an existing monkey.");return;} if(p.monkeyId===targetMonkeyId){showToast("A monkey cannot buff itself here.");return;} state.buffs.push({id:makeId("buff",state.nextBuffNumber++),targetMonkeyId,sourceMonkeyId:p.monkeyId,type:"income-buff",multiplier:1,flatBonus:0}); renderAll(); }); }
window.removeBuff=id=>{state.buffs=state.buffs.filter(b=>b.id!==id);renderAll();};

window.addSpecialAction=function(monkeyId,type){ const inst=state.monkeyInstances[monkeyId]; const selected=state.events.find(e=>e.id===state.selectedEventId); const round=selected?.round||state.settings.roundStart; const data={monkeyId,round,type,source:"manual",amount:0}; if(type==="hero-level")data.heroId=inst.heroId; else data.towerId=inst.towerId; const ev=makeEvent(data); state.events.push(ev); state.selectedEventId=ev.id; state.inspectorTab="action"; document.querySelectorAll("[data-inspector-tab]").forEach(o=>o.classList.toggle("active",o.dataset.inspectorTab==="action")); renderAll(); };
window.addAbilityAction=function(monkeyId,abilityId){ const inst=state.monkeyInstances[monkeyId]; const selected=state.events.find(e=>e.id===state.selectedEventId); const ev=makeEvent({monkeyId,towerId:inst.towerId,round:selected?.round||state.settings.roundStart,type:"ability",abilityId,source:"manual"}); state.events.push(ev); state.selectedEventId=ev.id; renderAll(); };
function addAbsorbAction(targetMonkeyId,sourceMonkeyId,round,mode){ if(targetMonkeyId===sourceMonkeyId){showToast("Target cannot absorb itself.");return;} const target=state.monkeyInstances[targetMonkeyId], source=state.monkeyInstances[sourceMonkeyId]; if(mode==="farms" && source.towerId!=="banana-farm"){showToast("This absorb interface only accepts farms.");return;} const ev=makeEvent({monkeyId:targetMonkeyId,towerId:target.towerId,heroId:target.heroId,round,type:"absorb",source:"manual",absorbedMonkeyIds:[sourceMonkeyId],absorbMode:mode}); state.events.push(ev); markAbsorbed(sourceMonkeyId,ev.id,"absorb",round); state.selectedEventId=ev.id; renderAll(); }
window.createParagonFromSelected=function(eventId){ const ev=state.events.find(e=>e.id===eventId); if(!ev)return; const t=getTower(ev.towerId); if(!t?.paragonAvailable||!allT5sExistBefore(t.id,ev.round)){showToast("Paragon requires all T5 paths before this action.");return;} const absorbed=Object.values(state.monkeyInstances).filter(i=>i.towerId===t.id && !getMonkeyStateAtRound(i.id,ev.round).sold).map(i=>i.id); const paragonId=makeId("monkey",state.nextMonkeyNumber++); const pIndex=state.nextParagonNumber++; state.monkeyInstances[paragonId]={id:paragonId,towerId:t.id,label:`${t.paragonName||t.name+" Paragon"} #${pIndex}`,kind:"paragon",paragonOf:t.id,paragonIndex:pIndex}; const pEvent=makeEvent({monkeyId:paragonId,towerId:t.id,round:ev.round,type:"paragon",source:"manual",cost:0,absorbedMonkeyIds:absorbed,paragonIndex:pIndex}); state.events.push(pEvent); absorbed.forEach(id=>markAbsorbed(id,pEvent.id,"paragon",ev.round,pIndex)); state.selectedEventId=pEvent.id; renderAll(); };
function markAbsorbed(monkeyId,eventId,kind,round,index=null){ const inst=state.monkeyInstances[monkeyId]; if(!inst)return; inst.absorbedBy=eventId; inst.absorbedKind=kind; inst.absorbedRound=round; inst.absorbedParagonIndex=index; state.paragonHistory[monkeyId]=state.paragonHistory[monkeyId]||[]; state.paragonHistory[monkeyId].push({eventId,kind,round,index}); }

window.addSellActionFromSelected=function(){ return toggleSellHereFromSelected(); };
window.toggleSellHereFromSelected=function(){ const ev=state.events.find(e=>e.id===state.selectedEventId); if(!ev||!ev.monkeyId)return; if(ev.type==="sell"){ state.events=state.events.filter(e=>e.id!==ev.id); state.selectedEventId=null; renderAll(); return; } const inst=state.monkeyInstances[ev.monkeyId]; const existing=state.events.find(e=>e.type==="sell"&&e.monkeyId===ev.monkeyId&&e.round===ev.round); if(existing){ state.events=state.events.filter(e=>e.id!==existing.id); state.selectedEventId=ev.id; renderAll(); return; } const stateAtEvent=getMonkeyStateAtRound(inst.id,ev.round); if(["place","place-hero","place-geraldo-item"].includes(ev.type)||(ev.type==="upgrade"&&ev.upgrade==="000")||!stateAtEvent.placed||stateAtEvent.sold){ showToast("Sell is unavailable on the 000/base placement."); return; } const sell=makeEvent({monkeyId:ev.monkeyId,towerId:inst.towerId,heroId:inst.heroId,round:ev.round,type:"sell",source:"manual",tick:ev.tick}); state.events.push(sell); state.selectedEventId=sell.id; renderAll(); };
window.deleteSelectedEvent=function(){ const ev=state.events.find(e=>e.id===state.selectedEventId); if(!ev)return; if(ev.type==="place"||ev.type==="place-hero"||ev.type==="place-geraldo-item"||ev.type==="paragon"){ state.events=state.events.filter(e=>e.monkeyId!==ev.monkeyId); state.buffs=state.buffs.filter(b=>b.targetMonkeyId!==ev.monkeyId&&b.sourceMonkeyId!==ev.monkeyId); delete state.monkeyInstances[ev.monkeyId]; } else { state.events=state.events.filter(e=>e.id!==ev.id); } state.selectedEventId=null; renderAll(); };

function sanitizePlanForRules(){
  for(const inst of Object.values({...state.monkeyInstances})){ if(inst.kind==="tower"){ const t=getTower(inst.towerId); if(!t || !t.enabled){ removeMonkey(inst.id); } } }
  state.events.forEach(ev=>{ if(ev.type==="upgrade"){ const t=getTower(ev.towerId); const clamped=clampUpgradeToRules(ev.upgrade,t); if(clamped!==ev.upgrade){ev.upgrade=clamped;ev.dirty=true;} } });
  enforceUniqueT5s(); cleanupOrphans();
}
function clampUpgradeToRules(up,t){ let d=up.split("").map(Number); PATH_KEYS.forEach(path=>{d[PATH_INDEX[path]]=clamp(d[PATH_INDEX[path]],0,t.maxPathTiers[path]??5);}); let next=d.join(""); while(!isUpgradePatternAllowed(next,t)){ const nums=next.split("").map(Number); const idx=nums.indexOf(Math.max(...nums)); nums[idx]=Math.max(0,nums[idx]-1); next=nums.join(""); } return next; }
function enforceUniqueT5s(){ const seen={}; state.events.filter(e=>e.type==="upgrade").sort((a,b)=>a.round-b.round||compareEvents(a,b)).forEach(ev=>{ const t=getTower(ev.towerId); const d=ev.upgrade.split("").map(Number); d.forEach((tier,idx)=>{ if(tier===5){ const key=`${ev.towerId}-${idx}`; seen[key]=seen[key]||new Set(); const limit=getT5Limit(ev.towerId,idx); if(!seen[key].has(ev.monkeyId) && seen[key].size>=limit){ d[idx]=4; ev.upgrade=d.join(""); ev.dirty=true; showToast("Duplicate T5 path was lowered to tier 4 by rules."); return; } seen[key].add(ev.monkeyId); } }); }); }
function getT5Limit(towerId,pathIdx){ let limit=clamp(Number(state.settings.players||1),1,4); if(towerId==="dart-monkey"&&pathIdx===2&&(state.settings.monkeyKnowledge||state.settings.selectedHero==="silas"))limit=Math.max(limit,2); return limit; }
function removeMonkey(id){ delete state.monkeyInstances[id]; state.events=state.events.filter(e=>e.monkeyId!==id); state.buffs=state.buffs.filter(b=>b.targetMonkeyId!==id&&b.sourceMonkeyId!==id); }
function cleanupOrphans(){ state.events=state.events.filter(e=>!e.monkeyId || state.monkeyInstances[e.monkeyId]); }
function sanitizeHeroesForSelection(){ Object.values(state.monkeyInstances).forEach(inst=>{ if(inst.kind==="hero"&&inst.heroId!==state.settings.selectedHero)removeMonkey(inst.id); }); if(state.settings.selectedHero!=="geraldo") Object.values(state.monkeyInstances).forEach(inst=>{ if(inst.kind==="geraldo-item")removeMonkey(inst.id); }); }
function removeEventsBeforeRoundStart(){ const before=state.settings.roundStart; const affected=new Set(state.events.filter(e=>e.round<before&&e.monkeyId).map(e=>e.monkeyId)); state.events=state.events.filter(e=>e.round>=before); affected.forEach(id=>{ if(!state.events.some(e=>e.monkeyId===id)) delete state.monkeyInstances[id]; }); cleanupOrphans(); }

function runCalculator(){ state.events=state.events.filter(e=>e.source!=="generated"); const id=placeNewTower("banana-farm",state.settings.roundStart,"generated"); if(id){ const ev=state.events.find(e=>e.monkeyId===id&&e.type==="place"); if(ev){ ev.source="generated"; ev.tick=0; } } renderAll(); showToast("Test calculate added a generated 000 farm at the earliest round."); }

function getMonkeyStateAtRound(monkeyId,round){ const evs=state.events.filter(e=>e.monkeyId===monkeyId&&e.round<=round).sort((a,b)=>a.round-b.round||compareEvents(a,b)); let placed=false,upgrade="000",sold=false; for(const ev of evs){ if(["place","place-hero","place-geraldo-item","paragon"].includes(ev.type)){placed=true;sold=false;if(ev.type==="paragon")upgrade="PARAGON";} if(ev.type==="upgrade"&&placed&&!sold)upgrade=ev.upgrade; if(ev.type==="sell"&&placed)sold=true; } return {placed,upgrade,sold}; }
function getNextAvailableUpgrade(current,tower,monkeyId,round){ for(const path of PATH_KEYS){ const next=addOneTier(current,path); if(next&&isUpgradePatternAllowed(next,tower)&&wouldNotBreakT5Limit(tower.id,next,monkeyId,round))return next; } return null; }
function addOneTier(up,path){ const d=up.split("").map(Number); const i=PATH_INDEX[path]; if(d[i]>=5)return null; d[i]++; return d.join(""); }
function changeUpgradeTier(up,path,delta){ const d=up.split("").map(Number); const i=PATH_INDEX[path]; d[i]+=delta; if(d[i]<0||d[i]>5)return null; return d.join(""); }
function isUpgradePatternAllowed(up,tower){ const d=up.split("").map(Number); if(d.some(v=>v<0||v>5))return false; if(tower){ for(const p of PATH_KEYS){ if(d[PATH_INDEX[p]]>(tower.maxPathTiers[p]??5))return false; } } const above=d.filter(v=>v>2).length, nonzero=d.filter(v=>v>0).length; if(above>1)return false; if(above===1&&nonzero>2)return false; return true; }
function wouldNotBreakT5Limit(towerId,up,monkeyId,round){ const d=up.split("").map(Number); for(let i=0;i<3;i++){ if(d[i]===5){ const existing=countT5s(towerId,i,round,monkeyId); if(existing>=getT5Limit(towerId,i))return false; } } return true; }
function countT5s(towerId,pathIdx,round,excludeMonkeyId=null){ return Object.values(state.monkeyInstances).filter(inst=>inst.towerId===towerId&&inst.id!==excludeMonkeyId).filter(inst=>{ const cur=getMonkeyStateAtRound(inst.id,round); return !cur.sold && cur.upgrade?.[pathIdx]==="5"; }).length; }
function allT5sExistBefore(towerId,round){ return [0,1,2].every(i=>countT5s(towerId,i,round,null)>=1); }
function isUpgradeAtLeast(up,min){ if(!min)return false; const d=up.split("").map(Number), m=min.split("").map(Number); return d.some((v,i)=>v>=m[i]&&m[i]>0); }
function hasAnyAvailablePath(t){ return t.enabled&&PATH_KEYS.some(p=>(t.maxPathTiers[p]??0)>0); }
function wouldBreakTowerLimits(towerId){ const total=Object.values(state.monkeyInstances).filter(i=>i.kind==="tower").length; if(total>=state.settings.maxTowers)return true; if(towerId==="banana-farm"&&countExistingTower("banana-farm")>=state.settings.maxBananaFarms)return true; if(towerId==="monkey-buccaneer"&&isBoatPlacementUnavailable())return true; return false; }
function isBoatPlacementUnavailable(){ return getBoatSpotLimit()<=0 || countExistingTower("monkey-buccaneer")>=getBoatSpotLimit(); }
function getBoatSpotLimit(){ return getMapBoatSpotLimit()+getLordOfAbyssBoatSpotLimit(); }
function getMapBoatSpotLimit(){ return Math.max(0,Number(state.settings.maxBoatSpots||0)); }
function getLordOfAbyssBoatSpotLimit(){ return Math.max(0,Number(state.settings.lordOfAbyss||0)); }
function countExistingTower(towerId){ return Object.values(state.monkeyInstances).filter(i=>i.towerId===towerId).length; }
function hasHeroPlaced(heroId){ return Object.values(state.monkeyInstances).some(i=>i.kind==="hero"&&i.heroId===heroId); }
function isExistingDragDisabled(inst,round){ if(!inst.absorbedBy)return false; const paragonOrAbsorb=state.events.find(e=>e.id===inst.absorbedBy); const sold=paragonOrAbsorb && state.events.some(e=>e.monkeyId===paragonOrAbsorb.monkeyId&&e.type==="sell"&&e.round<=round); return !sold && inst.absorbedRound<=round; }
function calculateSellValue(monkeyId,round){ const inst=state.monkeyInstances[monkeyId]; if(!inst)return 0; const rate=inst.kind==="tower"?getTower(inst.towerId).sellbackRate:.70; return Math.floor(calculateTotalSpentOnMonkeyUntilRound(monkeyId,round)*rate); }
function calculateTotalSpentOnMonkeyUntilRound(monkeyId,round){ return state.events.filter(e=>e.monkeyId===monkeyId&&e.round<=round&&e.type!=="sell").reduce((s,e)=>s+Math.max(0,-getMoneyDelta(e,round)),0); }
function getBuffsForMonkey(id){return state.buffs.filter(b=>b.targetMonkeyId===id)}
function compareEvents(a,b){ if(a.tick!==b.tick)return a.tick-b.tick; const order={"pop-income":0,"place":1,"place-hero":1,"place-geraldo-item":1,"upgrade":2,"hero-level":2,"bank-deposit":3,"bank-collect":4,"ability":5,"absorb":6,"paragon":7,"sell":8}; return (order[a.type]??9)-(order[b.type]??9)||a.sortOrder-b.sortOrder; }
function isSpecialEvent(e){return ["bank-collect","bank-deposit","absorb","paragon","ability","hero-level","pop-income"].includes(e.type)}
function getTower(id){return window.BTD6_TOWERS.find(t=>t.id===id)} function getHero(id){return window.BTD6_HEROES.find(h=>h.id===id)} function getSelectedHero(){return getHero(state.settings.selectedHero)} function getGeraldoItem(id){return window.BTD6_GERALDO_ITEMS.find(i=>i.id===id)}
function getInstanceMeta(inst,round=state.endRound){ if(inst.kind==="hero")return {iconKey:getHero(inst.heroId).iconKey,typeLabel:"Hero",category:"hero",absorbedVisible:false}; if(inst.kind==="geraldo-item")return {iconKey:getGeraldoItem(inst.itemId).iconKey,typeLabel:"Geraldo Item",category:"hero",absorbedVisible:false}; if(inst.kind==="paragon")return {iconKey:"paragon",typeLabel:"Paragon",category:"hero",absorbedVisible:false}; const t=getTower(inst.towerId); const visible=!!inst.absorbedBy && isExistingDragDisabled(inst,round); return {iconKey:t.iconKey,typeLabel:t.category,category:t.category,absorbedVisible:visible,absorbedText:inst.absorbedBy?`absorbed ${inst.absorbedKind}`:""}; }
function getHelperMeta(ev){ if(ev.type==="pop-income")return {iconKey:"popIncome",category:"helper"}; return {iconKey:"item",category:"helper"}; }
function formatMoney(v){return `$${Math.round(Number(v||0)).toLocaleString()}`}
function makeId(prefix,n){return `${prefix}-${n}`} function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
function showToast(msg){ el.toast.textContent=msg; el.toast.classList.remove("hidden"); clearTimeout(showToast.t); showToast.t=setTimeout(()=>el.toast.classList.add("hidden"),2300); }

const tutorialSteps=[
  {target:"header",title:"OptimalBtd6",text:"This top bar is where future calculators can live. Farming Planner is the active one right now."},
  {target:"left-panel",title:"Planner Setup",text:"Set the event type, goal, round start, cash, map difficulty, players, hero, and tower limits here."},
  {target:"right-panel",title:"Available / Existing / Rules",text:"Drag available cards into rounds, reuse existing monkeys for upgrades, and limit tower paths in Rules."},
  {target:"round-map",title:"Round Map",text:"Every important choice becomes a tick-sorted action: placements, upgrades, sells, bank actions, absorbs, abilities, paragons, and pop-income movement."},
  {target:"inspector",title:"Selected Action",text:"Click an action to edit its tick, upgrade tiers, special sub-actions, buffs, or delete/sell it."}
];
function startTutorial(){ state.tutorialIndex=0; showTutorialStep(); }
function showTutorialStep(){ document.querySelectorAll(".tutorial-highlight").forEach(e=>e.classList.remove("tutorial-highlight")); const step=tutorialSteps[state.tutorialIndex]; if(!step){endTutorial();return;} const target=document.querySelector(`[data-tutorial='${step.target}']`); if(target){ target.scrollIntoView({block:"nearest",inline:"nearest"}); target.classList.add("tutorial-highlight"); } el.tutorialTitle.textContent=step.title; el.tutorialText.textContent=step.text; el.tutorialNext.textContent=state.tutorialIndex===tutorialSteps.length-1?"Finish":"Next"; el.tutorialOverlay.classList.remove("hidden"); }
function nextTutorialStep(){ state.tutorialIndex++; showTutorialStep(); }
function endTutorial(){ document.querySelectorAll(".tutorial-highlight").forEach(e=>e.classList.remove("tutorial-highlight")); el.tutorialOverlay.classList.add("hidden"); }

init();
