const MAX_ROUND = 140;
const TICKS_PER_ROUND = 100;
const PATH_KEYS = ["top", "middle", "bottom"];
const PATH_INDEX = { top: 0, middle: 1, bottom: 2 };
const PATH_LABELS = { top: "Top", middle: "Middle", bottom: "Bottom" };

const state = {
  settings: {
    mode: "Timed", goal: "money", targetCashByRound: "", roundStart: 1, startingCash: 650,
    mapDifficulty: "Beginner", gameDifficulty: "Medium", players: 1, monkeyKnowledge: true, selectedHero: "quincy",
    maxTowers: 999, maxBananaFarms: 999, maxBoatSpots: 0, lordOfAbyss: 0
  },
  endRound: 40,
  events: [],
  monkeyInstances: {},
  buffs: [],
  paragonHistory: {},
  selectedEventId: null,
  selectedCumulative: null,
  inspectorTab: "action",
  nextEventNumber: 1,
  nextMonkeyNumber: 1,
  nextBuffNumber: 1,
  nextParagonNumber: 1,
  tutorialIndex: 0,
  roundMoneyTicks: {},
  activeRound: 1,
  centerTab: "editor",
  towerIncomeByTower: null,
  towerIncomeCache: new Map(),
  monkeyTimelineCache: new Map(),
  monkeyStateRoundCache: new Map(),
  monkeyStateMomentCache: new Map()
};

const el = {
  targetCashSubsection: document.getElementById("targetCashSubsection"), targetCashByRound: document.getElementById("targetCashByRound"),
  roundStart: document.getElementById("roundStart"), startingCash: document.getElementById("startingCash"), mapDifficulty: document.getElementById("mapDifficulty"), gameDifficulty: document.getElementById("gameDifficulty"), players: document.getElementById("players"),
  monkeyKnowledge: document.getElementById("monkeyKnowledge"), selectedHero: document.getElementById("selectedHero"), maxTowers: document.getElementById("maxTowers"), maxBananaFarms: document.getElementById("maxBananaFarms"), maxBoatSpots: document.getElementById("maxBoatSpots"), lordOfAbyss: document.getElementById("lordOfAbyss"),
  clearAllButton: document.getElementById("clearAllButton"),
  endRoundInput: document.getElementById("endRoundInput"), buildRoundsButton: document.getElementById("buildRoundsButton"), calculateButton: document.getElementById("calculateButton"),
  roundTableBody: document.getElementById("roundTableBody"), cumulativeList: document.getElementById("cumulativeList"), availableTowerList: document.getElementById("availableTowerList"), geraldoShelf: document.getElementById("geraldoShelf"), existingTowerList: document.getElementById("existingTowerList"), availabilityList: document.getElementById("availabilityList"), inspectorContent: document.getElementById("inspectorContent"), clearSelectionButton: document.getElementById("clearSelectionButton"), toast: document.getElementById("toast"),
  tutorialOverlay: document.getElementById("tutorialOverlay"), tutorialHighlight: document.getElementById("tutorialHighlight"), tutorialTitle: document.getElementById("tutorialTitle"), tutorialText: document.getElementById("tutorialText"), tutorialSkip: document.getElementById("tutorialSkip"), tutorialNext: document.getElementById("tutorialNext")
};

function init(){ hydrateIcons(); populateHeroes(); indexTowerIncomeValues(); bindGlobalControls(); bindTabs(); bindPanelResizers(); bindDragToDelete(); updateMonkeyKnowledgeIcon(); renderAll(); startTutorial(); }
function hydrateIcons(root=document){ root.querySelectorAll("[data-icon-key]").forEach(slot=>slot.innerHTML=iconHtml(slot.dataset.iconKey)); }
function iconHtml(key){ const e=window.BTD6_IMAGES?.[key]; if(!e) return `<span class="icon-fallback">❔</span>`; if(e.src) return `<img class="icon-img" src="${e.src}" alt="${key}" draggable="false" onerror="this.replaceWith(Object.assign(document.createElement('span'),{className:'icon-fallback',textContent:'${e.fallback||"●"}'}))">`; return `<span class="icon-fallback">${e.fallback||"●"}</span>`; }
function populateHeroes(){ el.selectedHero.innerHTML = window.BTD6_HEROES.map(h=>`<option value="${h.id}">${h.name}</option>`).join(""); el.selectedHero.value = state.settings.selectedHero; }

function bindGlobalControls(){
  document.querySelectorAll(".segment-option").forEach(button=>button.addEventListener("click",()=>{ const setting=button.dataset.setting, value=button.dataset.value; button.parentElement.querySelectorAll(".segment-option").forEach(o=>o.classList.remove("active")); button.classList.add("active"); state.settings[setting]=value; updateConditionalControls(); }));
  bindSettingInput(el.targetCashByRound,"targetCashByRound","string"); bindSettingInput(el.startingCash,"startingCash","number"); bindSettingInput(el.mapDifficulty,"mapDifficulty","string"); bindSettingInput(el.gameDifficulty,"gameDifficulty","string",()=>{ refreshVillageAbsorbTotals(); renderAll(); }); bindSettingInput(el.players,"players","number",()=>{ state.settings.players=clamp(state.settings.players,1,4); el.players.value=state.settings.players; sanitizePlanForRules(); }); bindSettingInput(el.maxTowers,"maxTowers","number",renderAll); bindSettingInput(el.maxBananaFarms,"maxBananaFarms","number",renderAll); bindSettingInput(el.maxBoatSpots,"maxBoatSpots","number",()=>{ state.settings.maxBoatSpots=Math.max(0,state.settings.maxBoatSpots); el.maxBoatSpots.value=state.settings.maxBoatSpots; renderAll(); });
  el.roundStart.addEventListener("change",()=>{ state.settings.roundStart=clamp(Number(el.roundStart.value||1),1,MAX_ROUND); el.roundStart.value=state.settings.roundStart; removeEventsBeforeRoundStart(); renderAll(); });
  el.monkeyKnowledge.addEventListener("change",()=>{ state.settings.monkeyKnowledge=el.monkeyKnowledge.checked; updateMonkeyKnowledgeIcon(); sanitizePlanForRules(); renderAll(); });
  el.lordOfAbyss.addEventListener("input",()=>{ state.settings.lordOfAbyss=Math.max(0,Number(el.lordOfAbyss.value||0)); el.lordOfAbyss.value=state.settings.lordOfAbyss; renderAll(); });
  el.selectedHero.addEventListener("change",()=>{ state.settings.selectedHero=el.selectedHero.value; sanitizeHeroesForSelection(); sanitizePlanForRules(); renderAll(); });
  el.endRoundInput.addEventListener("input",()=>{ state.endRound=clamp(Number(el.endRoundInput.value||1),1,MAX_ROUND); el.endRoundInput.value=state.endRound; });
  el.buildRoundsButton.addEventListener("click",()=>{ state.endRound=clamp(Number(el.endRoundInput.value||1),1,MAX_ROUND); el.endRoundInput.value=state.endRound; renderAll(); });
  el.calculateButton.addEventListener("click",runCalculator);
  el.clearAllButton.addEventListener("click",clearAllPlan);
  el.clearSelectionButton.addEventListener("click",()=>{ state.selectedEventId=null; state.selectedCumulative=null; renderInspector(); renderRoundTable(); renderCumulativeIfActive(); });
  document.querySelectorAll("[data-inspector-tab]").forEach(button=>button.addEventListener("click",()=>{ state.inspectorTab=button.dataset.inspectorTab; document.querySelectorAll("[data-inspector-tab]").forEach(o=>o.classList.toggle("active",o.dataset.inspectorTab===state.inspectorTab)); renderInspector(); }));
  el.tutorialSkip.addEventListener("click",endTutorial); el.tutorialNext.addEventListener("click",nextTutorialStep);
}
function bindSettingInput(element,key,type,after){ element.addEventListener("input",()=>{ state.settings[key]=type==="number"?Number(element.value||0):element.value; if(after) after(); renderRoundTable(); renderCumulativeIfActive(); }); }
function bindPanelResizers(){ const shell=document.querySelector(".app-shell"), right=document.querySelector(".right-panel"); if(!shell||!right)return; const root=document.documentElement; const drag=(options,startEvent)=>{ startEvent.preventDefault(); document.body.classList.add("is-resizing"); const startX=startEvent.clientX, startY=startEvent.clientY; const startLeft=parseFloat(getComputedStyle(root).getPropertyValue("--left-width"))||320; const startRight=parseFloat(getComputedStyle(root).getPropertyValue("--right-width"))||390; const startInspector=parseFloat(getComputedStyle(root).getPropertyValue("--inspector-height"))||320; const move=ev=>{ if(options.left) root.style.setProperty("--left-width",`${clamp(startLeft+ev.clientX-startX,220,520)}px`); if(options.right) root.style.setProperty("--right-width",`${clamp(startRight+(options.fromRight?ev.clientX-startX:startX-ev.clientX),260,620)}px`); if(options.inspector) root.style.setProperty("--inspector-height",`${clamp(startInspector+startY-ev.clientY,170,Math.max(220,right.clientHeight-170))}px`); }; const up=()=>{ document.body.classList.remove("is-resizing"); window.removeEventListener("mousemove",move); window.removeEventListener("mouseup",up); }; window.addEventListener("mousemove",move); window.addEventListener("mouseup",up); }; document.querySelectorAll("[data-resize]").forEach(handle=>handle.addEventListener("mousedown",ev=>drag({left:handle.dataset.resize==="left",right:handle.dataset.resize==="right"||handle.dataset.resize==="right-edge",fromRight:handle.dataset.resize==="right-edge",inspector:handle.dataset.resize==="inspector"},ev))); }

function updateMonkeyKnowledgeIcon(){ const icon=el.monkeyKnowledge?.closest(".toggle-row")?.querySelector("[data-icon-key]"); if(!icon)return; icon.dataset.iconKey=state.settings.monkeyKnowledge?"mk":"mkOff"; icon.innerHTML=iconHtml(icon.dataset.iconKey); }
function bindTabs(){ document.querySelectorAll("[data-center-tab]").forEach(b=>b.addEventListener("click",()=>setTab("center",b.dataset.centerTab))); document.querySelectorAll("[data-right-tab]").forEach(b=>b.addEventListener("click",()=>setTab("right",b.dataset.rightTab))); }
function setTab(side,tab){ const buttonSelector=side==="center"?"[data-center-tab]":"[data-right-tab]"; const ids=side==="center"?["editorTab","cumulativeTab"]:["availableTab","existingTab","availabilityTab"]; if(side==="center")state.centerTab=tab; document.querySelectorAll(buttonSelector).forEach(b=>b.classList.toggle("active",(side==="center"?b.dataset.centerTab:b.dataset.rightTab)===tab)); ids.forEach(id=>document.getElementById(id).classList.toggle("active",id===`${tab}Tab`)); if(tab==="cumulative")renderCumulative(); if(tab==="existing")renderExistingTowers(); }
function updateConditionalControls(){ const show=state.settings.mode==="Least Cash"||state.settings.mode==="Least Tiers"; el.targetCashSubsection.classList.toggle("hidden",!show); }
function renderAll(){ resetTransientCaches(); updateConditionalControls(); renderAvailableTowers(); renderExistingTowers(); renderAvailabilityRules(); renderRoundTable(false); renderCumulativeIfActive(); renderInspector(); }
function resetTransientCaches(){ state.towerIncomeCache=new Map(); state.monkeyTimelineCache=new Map(); state.monkeyStateRoundCache=new Map(); state.monkeyStateMomentCache=new Map(); }
function renderCumulativeIfActive(){ if(state.centerTab==="cumulative")renderCumulative(); }
function ensureActiveRound(){ state.activeRound=clamp(Number(state.activeRound||state.settings.roundStart),state.settings.roundStart,state.endRound); return state.activeRound; }
function indexTowerIncomeValues(){ state.towerIncomeByTower={}; (window.BTD6_TOWER_INCOME_VALUES||[]).forEach((entry,entryIndex)=>{ (state.towerIncomeByTower[entry.towerId]=state.towerIncomeByTower[entry.towerId]||[]).push({...entry,entryIndex}); }); }

function renderAvailableTowers(){
  el.availableTowerList.innerHTML="";
  el.availableTowerList.appendChild(availableCard({type:"helper-pop-income", id:"pop-income", iconKey:"popIncome", priceLabel:"Pop", category:"helper"}));
  const hero=getSelectedHero(); if(hero && hero.id!=="none" && !hasHeroPlaced(hero.id)) el.availableTowerList.appendChild(availableCard({type:"hero", id:hero.id, iconKey:hero.iconKey, price:priceWithDifficulty(hero.baseCost||0), title:hero.name, disabled:wouldBreakTowerLimits(), category:"hero"}));
  window.BTD6_TOWERS.forEach(t=>{ const disabled=!t.enabled||!hasAnyAvailablePath(t)||wouldBreakTowerLimits(t.id); el.availableTowerList.appendChild(availableCard({type:"tower",id:t.id,iconKey:t.iconKey,price:priceWithDifficulty(t.baseCost),title:t.name,disabled,category:t.category})); });
  renderGeraldoShelf();
}
function availableCard(data){ const card=document.createElement("div"); card.className=`available-tower ${categoryClass(data.category)} ${data.disabled?"disabled":""}`; card.draggable=!data.disabled; card.title=data.title||data.id; card.innerHTML=`<div class="available-icon">${iconHtml(data.iconKey)}</div><div class="available-price">${data.priceLabel||formatMoney(data.price||0)}</div>`; card.addEventListener("dragstart",ev=>{ if(data.disabled){ev.preventDefault();return;} ev.dataTransfer.setData("text/plain",JSON.stringify({type:data.type,id:data.id})); }); return card; }
function renderGeraldoShelf(){ el.geraldoShelf.innerHTML=""; if(state.settings.selectedHero!=="geraldo")return; el.geraldoShelf.innerHTML=`<details open><summary>Geraldo Goodies</summary><div class="geraldo-items" id="geraldoItems"></div></details>`; const list=document.getElementById("geraldoItems"); window.BTD6_GERALDO_ITEMS.forEach(item=>list.appendChild(availableCard({type:"geraldo-item",id:item.id,iconKey:item.iconKey,price:priceWithDifficulty(item.cost),title:item.name,category:"hero"}))); }

function renderExistingTowers(){
  el.existingTowerList.innerHTML=""; const instances=Object.values(state.monkeyInstances).sort((a,b)=>a.label.localeCompare(b.label));
  if(!instances.length){el.existingTowerList.innerHTML=`<div class="empty-inspector">No existing monkeys yet.</div>`;return;}
  instances.forEach(inst=>{ const meta=getInstanceMeta(inst); const current=getMonkeyStateAtRound(inst.id,state.endRound); const absorbedBlocked=isExistingDragDisabled(inst,state.endRound); const sold=current.sold; const card=document.createElement("div"); card.className=`existing-card ${categoryClass(meta.category)} ${sold?"sold":""} ${absorbedBlocked?"disabled":""} ${meta.absorbedVisible?"absorbed":""}`; card.draggable=true; card.innerHTML=`<div class="card-title">${iconHtml(meta.iconKey)}<span>${inst.label}</span></div><div class="card-meta">${meta.typeLabel} · ${sold?"Sold":current.upgrade||"No paths"}${meta.absorbedText?` · ${meta.absorbedText}`:""}</div>`; card.addEventListener("click",()=>window.selectCumulative(inst.id,state.endRound)); card.addEventListener("dragstart",ev=>{ ev.dataTransfer.setData("text/plain",JSON.stringify({type:"existing-monkey",monkeyId:inst.id})); }); el.existingTowerList.appendChild(card); });
}
function renderAvailabilityRules(){ el.availabilityList.innerHTML=""; window.BTD6_TOWERS.forEach(t=>{ const card=document.createElement("div"); card.className="availability-card"; card.innerHTML=`<div class="availability-icon">${iconHtml(t.iconKey)}</div><div><div class="availability-name-row"><span>${t.name}</span><label class="mini-check"><input type="checkbox" data-rule="tower" data-tower-id="${t.id}" ${t.enabled?"checked":""}>Enabled</label></div><div class="tier-stack">${tierControlHtml("availability",t.id,"top",t.maxPathTiers.top,false)}${tierControlHtml("availability",t.id,"middle",t.maxPathTiers.middle,false)}${tierControlHtml("availability",t.id,"bottom",t.maxPathTiers.bottom,false)}</div></div>`; card.querySelector("[data-rule='tower']").addEventListener("change",ev=>{ getTower(ev.target.dataset.towerId).enabled=ev.target.checked; sanitizePlanForRules(); renderAll(); }); el.availabilityList.appendChild(card); }); }
function tierControlHtml(kind,id,path,value,showParagon=false,paragonReady=false,paragonActive=false,currentUpgrade=null){ const plusDisabled=kind==="selected"&&(deltaWouldLockCrosspath(currentUpgrade,path,1)||selectedTierIncreaseLocked(id,path)); const minusDisabled=kind==="selected"&&selectedTierDecreaseLocked(id,path); const lockTitle=plusDisabled?(selectedTierIncreaseLocked(id,path)?"Use the Monkeyopolis Upgrade button in the farm absorb interface.":"Only two upgrade paths can be selected on one tower."):""; const minusTitle=minusDisabled?"Village bottom path is locked once farm absorption is available.":""; return `<div class="tier-control ${showParagon?"":"no-paragon"} ${plusDisabled||minusDisabled?"path-locked":""}"><span class="tier-label">${PATH_LABELS[path]}</span><button class="step-btn" ${minusDisabled?`disabled title="${minusTitle}"`:""} onclick="changeTierValue('${kind}','${id}','${path}',-1)">−</button><span class="tier-value">${value}</span><button class="step-btn" ${plusDisabled?`disabled title="${lockTitle}"`:""} onclick="changeTierValue('${kind}','${id}','${path}',1)">+</button>${showParagon?`<button class="paragon-btn ${paragonReady?"ready":""} ${paragonActive?"active":""}" ${paragonReady?"":"disabled"} onclick="createParagonFromSelected('${id}')">${iconHtml("paragon")}</button>`:""}</div>`; }
window.changeTierValue=function(kind,id,path,delta){
  if(kind==="availability"){ const t=getTower(id); t.maxPathTiers[path]=clamp(t.maxPathTiers[path]+delta,0,5); sanitizePlanForRules(); renderAll(); return; }
  if(kind==="selected"){
    const ev=state.events.find(e=>e.id===id); if(!ev||!["upgrade","snapshot"].includes(ev.type))return;
    const current=ev.upgrade||ev.snapshotUpgrade||"000"; if(ev.type==="snapshot"&&isFinalUpgrade(current)){showToast("Final upgrade snapshots can only be sold.");return;}
    const t=getTower(ev.towerId); if(delta<0&&isVillageBottomDowngradeLocked(ev,path,current)){showToast("Village bottom path is locked once farm absorption is available.");return;} const next=changeUpgradeTier(current,path,delta);
    if(!next||!isUpgradePatternAllowed(next,t)||!wouldNotBreakT5Limit(ev.towerId,next,ev.monkeyId,ev.round)){showToast("That upgrade breaks path/rule limits.");return;}
    if(isVillage005UpgradeBlocked(ev,next)){showToast("Use the Monkeyopolis Upgrade button after pending at least one absorbed farm.");return;}
    const before={type:ev.type,upgrade:ev.upgrade,fromUpgrade:ev.fromUpgrade,snapshotUpgrade:ev.snapshotUpgrade};
    if(ev.type==="snapshot"){
      if(!isUpgradeGreaterOrEqual(next,ev.snapshotUpgrade||"000")||next===(ev.snapshotUpgrade||"000")){showToast("Snapshots can only become higher upgrades.");return;}
      ev.type="upgrade"; ev.fromUpgrade=ev.snapshotUpgrade||"000"; delete ev.snapshotUpgrade; ev.upgrade=next;
    } else {
      ev.upgrade=next;
    }
    resetTransientCaches();
    const err=validateMonkeyTimeline(ev.monkeyId); if(err){ Object.assign(ev,before); resetTransientCaches(); showToast(err); return; }
    ev.dirty=true; sanitizePlanForRules(); renderAll();
  }
};

function renderRoundTable(resetCaches=true){ if(resetCaches)resetTransientCaches(); const activeRound=ensureActiveRound(); const rows=calculateRows(); const rowsByRound=new Map(rows.map(row=>[row.round,row])); el.roundTableBody.innerHTML=""; for(let r=state.settings.roundStart;r<=state.endRound;r++){ const row=rowsByRound.get(r); if(!row)continue; const isActive=r===activeRound; const tick=clamp(Number(state.roundMoneyTicks[r]??0),0,TICKS_PER_ROUND); const currentMoney=isActive?calculateMoneyAtRoundTick(row,tick):row.endMoney; const rowClasses=`round-row ${row.conflict?"conflict":"ok"} ${isActive?"active-round":""}`; const summaryRow=document.createElement("tr"); summaryRow.className=`${rowClasses} round-summary-row`; summaryRow.dataset.round=r; summaryRow.title=isActive?"This round is active for tick-by-tick money calculations.":"Click this round to make it the only active tick calculator."; summaryRow.innerHTML=`<td><strong>${r}</strong>${isActive?`<span class="active-round-badge">Active</span>`:""}</td><td class="money-cell">${formatMoney(row.startMoney)}</td><td class="money-cell">${formatMoney(row.popIncome)}</td><td class="money-cell">${formatMoney(row.roundIncome)}</td><td class="money-cell">${formatMoney(row.endIncome)}</td><td>${roundMoneyHtml(r,tick,currentMoney,isActive)}</td><td class="money-cell">${formatMoney(row.endMoney)}</td>`; const actionRow=document.createElement("tr"); actionRow.className=`${rowClasses} round-action-row`; actionRow.dataset.round=r; actionRow.title=summaryRow.title; actionRow.innerHTML=`<td class="round-action-cell" colspan="7"><div class="round-actions">${renderEventChipsForRound(r)}</div></td>`; bindRoundActivation(summaryRow,r); bindRoundActivation(actionRow,r); bindDropHandlers(summaryRow,r); bindDropHandlers(actionRow,r); el.roundTableBody.appendChild(summaryRow); el.roundTableBody.appendChild(actionRow); if(isActive)bindRoundEditors(summaryRow,r,row); } }
function roundMoneyHtml(round,tick,currentMoney,isActive){ return isActive?roundMoneySliderHtml(round,tick,currentMoney):`<button class="round-money-static" type="button" onclick="activateRound(${round})"><span class="round-money-value">${formatMoney(currentMoney)}</span><span class="round-money-note">Click to activate ticks</span></button>`; }
function roundMoneySliderHtml(round,tick,currentMoney){ return `<div class="round-money-editor active"><div class="round-money-value">${formatMoney(currentMoney)}</div><div class="round-money-note">Only active round calculates ticks</div><div class="round-money-controls"><input class="round-money-slider" data-round="${round}" type="range" min="0" max="${TICKS_PER_ROUND}" value="${tick}"><input class="round-money-tick" data-round="${round}" type="number" min="0" max="${TICKS_PER_ROUND}" value="${tick}"></div></div>`; }
function bindRoundActivation(row,round){ row.addEventListener("click",ev=>{ if(ev.target.closest("button,input,select,textarea,a"))return; activateRound(round); }); }
window.activateRound=function(round){ const next=clamp(Number(round||state.settings.roundStart),state.settings.roundStart,state.endRound); if(state.activeRound===next)return; state.activeRound=next; renderRoundTable(); };
function bindRoundEditors(row,round,rowData){
  const slider=row.querySelector(".round-money-slider"), input=row.querySelector(".round-money-tick"), value=row.querySelector(".round-money-value");
  const updateTick=(v,rerender=false)=>{ const tick=clamp(Number(v||0),0,TICKS_PER_ROUND); state.roundMoneyTicks[round]=tick; if(slider)slider.value=tick; if(input)input.value=tick; if(value&&rowData)value.textContent=formatMoney(calculateMoneyAtRoundTick(rowData,tick)); if(rerender)renderRoundTable(); };
  slider?.addEventListener("input",e=>updateTick(e.target.value,false)); slider?.addEventListener("change",e=>updateTick(e.target.value,true));
  input?.addEventListener("input",e=>updateTick(e.target.value,false)); input?.addEventListener("change",e=>updateTick(e.target.value,true));
}
function escapeAttr(value){ return String(value).replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/</g,"&lt;"); }

function renderEventChipsForRound(round){ const events=state.events.filter(e=>e.round===round && !(e.type==="absorb"&&e.absorbMode==="farms")).sort(compareEvents); if(!events.length)return `<span class="empty-drop-zone">Drop action here</span>`; return events.map(eventChipHtml).join(""); }
function eventChipHtml(ev){ const m=ev.monkeyId?state.monkeyInstances[ev.monkeyId]:null; const meta=m?getInstanceMeta(m):getHelperMeta(ev); const selected=state.selectedEventId===ev.id?"selected":""; const classes=["action-chip",categoryClass(meta.category),selected,ev.source==="generated"?"generated":"",ev.dirty?"dirty":"",ev.type==="sell"?"sell":"",isSpecialEvent(ev)?"special":"",meta.absorbedVisible?"absorbed":""].filter(Boolean).join(" "); const price=eventPriceLabel(ev); const attrs=`draggable="true" ondragstart="dragEventChip(event,'${ev.id}')" onclick="selectEvent('${ev.id}')"`; return `<button class="${classes}" ${attrs}>${iconHtml(meta.iconKey)}<span class="chip-title">${eventLabel(ev,m)}</span>${price?`<span class="chip-price">${price}</span>`:""}<span class="tick-badge">@${ev.tick}</span></button>`; }
function eventLabel(ev,m){ if(ev.type==="place")return `Place ${m.label}`; if(ev.type==="place-hero")return `Place ${m.label}`; if(ev.type==="place-geraldo-item")return `Buy ${m.label}`; if(ev.type==="snapshot")return `${m.label} <span class="upgrade-code">${ev.snapshotUpgrade||"000"}</span>`; if(ev.type==="upgrade")return `${m.label} <span class="upgrade-code">${ev.fromUpgrade||getPreviousUpgradeBefore(ev)}</span> → <span class="upgrade-code">${ev.upgrade}</span>`; if(ev.type==="hero-level")return `Skip ${m.label} Levels`; if(ev.type==="sell")return `Sell ${m.label}`; if(ev.type==="bank-collect")return `Collect ${m.label} Bank`; if(ev.type==="bank-deposit")return `Deposit ${m.label} Bank`; if(ev.type==="absorb")return `Absorb into ${m.label}`; if(ev.type==="paragon")return `Create ${m.label}`; if(ev.type==="ability")return `Use ${m.label} Ability`; if(ev.type==="pop-income")return `Pop Income ${formatMoney(ev.amount||0)}${ev.averageSplit?" Avg Split":""}`; if(ev.type==="tower-income")return ""; return ev.type; }
function eventPriceLabel(ev){ const delta=getMoneyDelta(ev,ev.round); if(ev.type==="sell"||ev.type==="tower-income")return ""; if(ev.type==="pop-income")return formatMoney(delta); if(delta<0)return formatMoney(Math.abs(delta)); if(delta>0)return formatMoney(delta); return ""; }
function categoryClass(category){ return `cat-${String(category||"helper").toLowerCase().replace(/[^a-z0-9]+/g,"-")}`; }
function bindDropHandlers(row,round){ row.addEventListener("dragover",ev=>{ev.preventDefault();row.classList.add("drop-hover")}); row.addEventListener("dragleave",()=>row.classList.remove("drop-hover")); row.addEventListener("drop",ev=>{ev.preventDefault();row.classList.remove("drop-hover"); const raw=ev.dataTransfer.getData("text/plain"); if(!raw)return; const p=JSON.parse(raw); if(p.type==="tower")placeNewTower(p.id,round,"manual"); if(p.type==="hero")placeHero(p.id,round); if(p.type==="geraldo-item")placeGeraldoItem(p.id,round); if(p.type==="helper-pop-income")addPopIncomeAction(round); if(p.type==="existing-monkey")handleExistingDrop(p.monkeyId,round); if(p.type==="event-action")moveEventToRound(p.eventId,round); }); }

window.dragEventChip=function(ev,eventId){ ev.dataTransfer.setData("text/plain",JSON.stringify({type:"event-action",eventId})); ev.dataTransfer.effectAllowed="move"; };
function moveEventToRound(eventId,round){ const ev=state.events.find(e=>e.id===eventId); if(!ev)return; const oldRound=ev.round; ev.round=clamp(Number(round||state.settings.roundStart),state.settings.roundStart,MAX_ROUND); state.activeRound=ev.round; resetTransientCaches(); const err=validateMonkeyTimeline(ev.monkeyId); if(err){ ev.round=oldRound; state.activeRound=oldRound; resetTransientCaches(); showToast(err); return; } ev.dirty=true; state.selectedEventId=ev.id; renderAll(); }

function placeNewTower(towerId,round,source="manual"){ const t=getTower(towerId); if(!t.enabled||!hasAnyAvailablePath(t)){showToast("Tower disabled by rules.");return null;} if(wouldBreakTowerLimits(towerId)){showToast("Tower limit would be exceeded.");return null;} state.activeRound=round; const id=makeId("monkey",state.nextMonkeyNumber++); const label=`${t.shortName||t.name} #${countExistingTower(towerId)+1}`; state.monkeyInstances[id]={id,towerId,label,kind:"tower"}; const ev=makeEvent({monkeyId:id,towerId,round,type:"place",upgrade:"000",source}); state.events.push(ev); renderAll(); return id; }
function placeHero(heroId,round){ const h=getHero(heroId); if(hasHeroPlaced(heroId)){showToast("That hero is already placed.");return;} if(wouldBreakTowerLimits()){showToast("Tower limit would be exceeded. Max Towers includes the hero.");return;} state.activeRound=round; const id=makeId("monkey",state.nextMonkeyNumber++); state.monkeyInstances[id]={id,heroId,label:h.name,kind:"hero"}; state.events.push(makeEvent({monkeyId:id,heroId,round,type:"place-hero",source:"manual"})); renderAll(); }
function placeGeraldoItem(itemId,round){ state.activeRound=round; const item=getGeraldoItem(itemId); const id=makeId("monkey",state.nextMonkeyNumber++); state.monkeyInstances[id]={id,itemId,label:item.name,kind:"geraldo-item"}; state.events.push(makeEvent({monkeyId:id,itemId,round,type:"place-geraldo-item",source:"manual"})); renderAll(); }
function addPopIncomeAction(round){ state.activeRound=round; state.events.push(makeEvent({round,type:"pop-income",amount:0,averageSplit:false,source:"manual"})); renderAll(); }
function handleExistingDrop(monkeyId,round){ const inst=state.monkeyInstances[monkeyId]; if(!inst)return; if(inst.kind==="hero"){ addHeroLevelAction(monkeyId,round); return; } if(inst.kind!=="tower"){ showToast("This object has no upgrade path."); return; } const current=getMonkeyStateAtRound(monkeyId,round); if(current.sold){showToast("This tower was sold before this point and cannot be added here.");return;} if(!current.placed){showToast("This tower has not been placed before this point.");return;} if(isExistingDragDisabled(inst,round)){showToast("This tower is absorbed at this point and cannot be dragged after the absorb.");return;} const ev=makeEvent({monkeyId,towerId:inst.towerId,round,type:"snapshot",snapshotUpgrade:current.upgrade,source:"manual"}); state.events.push(ev); state.activeRound=round; resetTransientCaches(); const err=validateMonkeyTimeline(monkeyId); if(err){ state.events=state.events.filter(e=>e.id!==ev.id); resetTransientCaches(); showToast(err); return; } state.selectedEventId=ev.id; renderAll(); }
function addHeroLevelAction(monkeyId,round){ state.activeRound=round; state.events.push(makeEvent({monkeyId,heroId:state.monkeyInstances[monkeyId].heroId,round,type:"hero-level",moneySpent:0,source:"manual"})); renderAll(); }
function makeEvent(data){ return {id:makeId("event",state.nextEventNumber++),tick:0,sortOrder:Date.now()+Math.random(),dirty:false,...data}; }

function calculateRows(){ refreshVillageAbsorbTotals(); const rows=[]; let money=Number(state.settings.startingCash||0); let bankState={}; const activeRound=ensureActiveRound(); for(let r=state.settings.roundStart;r<=state.endRound;r++){ const startMoney=money; const bankStart=cloneBankState(bankState); const popBase=Number(window.BTD6_ROUND_POP_INCOME?.[r]||0); const endIncome=getEndOfRoundIncome(r); const result=simulateRoundMoney(r,startMoney,null,true,bankState,{expandTowerIncome:r===activeRound}); money=result.money; bankState=result.bankState; rows.push({round:r,startMoney,bankStart,popIncome:popBase,endIncome,roundIncome:result.roundIncome,endMoney:money,conflict:result.conflict}); } return rows; }
function simulateRoundMoney(round,startMoney,throughTick=null,includeEnd=true,startingBankState={},options={}){ let money=Number(startMoney||0), conflict=false, roundIncome=0; const bankState=cloneBankState(startingBankState); const popBase=Number(window.BTD6_ROUND_POP_INCOME?.[round]||0); const events=getEventsForRound(round,{expandTowerIncome:options.expandTowerIncome!==false}); let movedPop=0; for(const ev of events){ if(ev.type==="pop-income"){ const amount=clamp(Number(ev.amount||0),0,Math.max(0,popBase-movedPop)); ev.amount=amount; movedPop+=amount; } } const remainingPop=Math.max(0,popBase-movedPop); const incomeTicks=[]; const timedPopEvents=[]; const simEvents=events.concat(timedPopEvents).sort(compareEvents); let averagePopEarned=0; const averagePopEvents=events.filter(e=>e.type==="pop-income"&&e.averageSplit); const addAveragePopThroughTick=tick=>{ const avgIncome=averagePopEvents.reduce((sum,e)=>sum+Number(e.amount||0)*(clamp(tick,0,TICKS_PER_ROUND)/TICKS_PER_ROUND),0); const newlyEarned=Math.max(0,avgIncome-averagePopEarned); money+=newlyEarned; averagePopEarned+=newlyEarned; }; for(const ev of simEvents){ if(throughTick!==null && ev.tick>throughTick)break; addAveragePopThroughTick(ev.tick); const bankHandled=applyBankEvent(ev,round,bankState,money); if(bankHandled){ money=bankHandled.money; roundIncome+=Number(bankHandled.incomeDelta||0); conflict=conflict||bankHandled.conflict; continue; } const delta=ev.type==="pop-income"&&ev.averageSplit?0:getMoneyDelta(ev,round); if(delta<0 && money+delta<0)conflict=true; money+=delta; if(isRoundIncomeEvent(ev))roundIncome+=Math.max(0,delta); if(money<0)conflict=true; } if(throughTick!==null){ addAveragePopThroughTick(throughTick); } if(throughTick===null && includeEnd){ const totalAverage=averagePopEvents.reduce((sum,e)=>sum+Number(e.amount||0),0); const remainingAverage=Math.max(0,totalAverage-averagePopEarned); money+=remainingAverage; if(!incomeTicks.length){ money+=remainingPop; } const endCash=getEndOfRoundCashIncome(round,bankState); money+=endCash.cash; applyEndOfRoundBankInterest(round,bankState); } return {money,bankState,conflict,roundIncome}; }
function calculateMoneyAtRoundTick(row,tick){ return simulateRoundMoney(row.round,row.startMoney,clamp(Number(tick||0),0,TICKS_PER_ROUND),false,row.bankStart||{}).money; }
function isRoundIncomeEvent(ev){ return ev.type==="round-pop-income"||ev.type==="tower-income"; }
function getMoneyDelta(ev,round){ if(ev.type==="round-pop-income")return Number(ev.amount||0); if(ev.type==="tower-income")return Number(ev.amount||0); if(ev.type==="place")return -priceWithDifficulty(getTower(ev.towerId).baseCost||0); if(ev.type==="place-hero")return -priceWithDifficulty(getHero(ev.heroId).baseCost||0); if(ev.type==="place-geraldo-item")return -priceWithDifficulty(getGeraldoItem(ev.itemId).cost||0); if(ev.type==="snapshot")return 0; if(ev.type==="upgrade")return -calculateUpgradeCostForEvent(ev); if(ev.type==="sell")return calculateSellValue(ev.monkeyId,round,Math.max(0,ev.tick-1)); if(ev.type==="hero-level")return -Number(ev.moneySpent||0); if(ev.type==="bank-deposit"||ev.type==="bank-collect")return getBankActionDeltaAtEvent(ev); if(ev.type==="pop-income")return Number(ev.amount||0); if(ev.type==="paragon")return -priceWithDifficulty(ev.cost||0); return 0; }
function getEndOfRoundIncome(round){ return 100 + round + getTowerIncomeForRound(round,{endIncomeOnly:true}).filter(item=>!isBankUpgrade(item.inst.towerId,getMonkeyStateAtMoment(item.inst.id,round,TICKS_PER_ROUND).upgrade)).reduce((sum,item)=>sum+item.amount,0); }
function getEndOfRoundCashIncome(round,bankState){ let cash=100+round, income=100+round; getTowerIncomeForRound(round,{endIncomeOnly:true}).forEach(item=>{ const cur=getMonkeyStateAtMoment(item.inst.id,round,TICKS_PER_ROUND); if(isBankUpgrade(item.inst.towerId,cur.upgrade)){ const account=ensureBankState(bankState,item.inst.id); const cap=getBankCapacity(cur.upgrade); const before=account.bankMoney; account.bankMoney+=Number(item.amount||0); account.eligibleInterest+=Number(item.amount||0); clampBankAccount(account,cap); income+=Math.max(0,account.bankMoney-before); } else { cash+=Number(item.amount||0); income+=Number(item.amount||0); } }); return {cash,income}; }
function getEventsForRound(round,{expandTowerIncome=true}={}){ const towerIncome=expandTowerIncome?getTowerIncomeEventsForRound(round):getAggregateTowerIncomeEventsForRound(round); return state.events.filter(e=>e.round===round).concat(towerIncome).sort(compareEvents); }
function getTowerIncomeEventsForRound(round){ return getTowerIncomeForRound(round,{timedOnly:true}).map((item,idx)=>({id:`tower-income-${round}-${item.inst.id}-${item.entryIndex}-${item.tickIndex}`,round,tick:item.tick,sortOrder:idx,type:"tower-income",source:"generated",monkeyId:item.inst.id,towerId:item.inst.towerId,amount:item.amount,bankIncome:isBankUpgrade(item.inst.towerId,getMonkeyStateAtMoment(item.inst.id,round,item.tick).upgrade)})); }
function getAggregateTowerIncomeEventsForRound(round){ if(!state.towerIncomeByTower)indexTowerIncomeValues(); const grouped=new Map(); const add=(inst,amount,bankIncome)=>{ if(!amount)return; const key=`${inst.id}|${bankIncome?1:0}`; const existing=grouped.get(key)||{id:`tower-income-${round}-${inst.id}-${bankIncome?"bank":"cash"}`,round,tick:TICKS_PER_ROUND,sortOrder:0,type:"tower-income",source:"generated",monkeyId:inst.id,towerId:inst.towerId,amount:0,bankIncome}; existing.amount+=Number(amount||0); grouped.set(key,existing); }; Object.values(state.monkeyInstances).forEach(inst=>{ if(inst.kind!=="tower")return; const cur=getMonkeyStateAtMoment(inst.id,round,TICKS_PER_ROUND); if(!cur.placed||cur.sold||cur.upgrade==="PARAGON")return; (state.towerIncomeByTower?.[inst.towerId]||[]).forEach(entry=>{ if(isTowerEndIncomeEntry(entry))return; if(entry.rounds&&!entry.rounds.includes(round))return; if(entry.fromRound&&round<entry.fromRound)return; if(entry.toRound&&round>entry.toRound)return; if(entry.exactUpgrade&&cur.upgrade!==entry.exactUpgrade)return; if(entry.minUpgrade&&!isUpgradeAtLeast(cur.upgrade,entry.minUpgrade))return; const total=normalizeTowerIncomeTicks(entry).reduce((sum,_,tickIndex)=>sum+getTowerIncomeAmount(entry,tickIndex),0); add(inst,total,isBankUpgrade(inst.towerId,cur.upgrade)); }); if(inst.towerId==="monkey-village"&&isUpgradeAtLeast(cur.upgrade,"005"))add(inst,10*getMonkeyopolisCrateValue(inst.id,round),false); }); return Array.from(grouped.values()).map((ev,idx)=>({...ev,sortOrder:idx})); }
function getTowerIncomeForRound(round,{timedOnly=false,endIncomeOnly=false}={}){ const cacheKey=`${round}|${timedOnly?1:0}|${endIncomeOnly?1:0}`; if(state.towerIncomeCache?.has(cacheKey))return state.towerIncomeCache.get(cacheKey); if(!state.towerIncomeByTower)indexTowerIncomeValues(); const items=[]; Object.values(state.monkeyInstances).forEach(inst=>{ if(inst.kind!=="tower")return; const values=state.towerIncomeByTower?.[inst.towerId]||[]; values.forEach(entry=>{ if(entry.rounds&&!entry.rounds.includes(round))return; if(entry.fromRound&&round<entry.fromRound)return; if(entry.toRound&&round>entry.toRound)return; const endIncome=isTowerEndIncomeEntry(entry); if(timedOnly&&endIncome)return; if(endIncomeOnly&&!endIncome)return; const ticks=endIncome?[TICKS_PER_ROUND]:normalizeTowerIncomeTicks(entry); ticks.forEach((tick,tickIndex)=>{ const cur=getMonkeyStateAtMoment(inst.id,round,tick); if(!cur.placed||cur.sold||cur.upgrade==="PARAGON")return; if(entry.exactUpgrade&&cur.upgrade!==entry.exactUpgrade)return; if(entry.minUpgrade&&!isUpgradeAtLeast(cur.upgrade,entry.minUpgrade))return; items.push({inst,entry,entryIndex:entry.entryIndex,tickIndex,tick,amount:getTowerIncomeAmount(entry,tickIndex)}); }); }); }); addMonkeyopolisIncomeForRound(items,round,{timedOnly,endIncomeOnly}); state.towerIncomeCache?.set(cacheKey,items); return items; }
function addMonkeyopolisIncomeForRound(items,round,{timedOnly=false,endIncomeOnly=false}={}){ if(endIncomeOnly)return; Object.values(state.monkeyInstances).forEach(inst=>{ if(inst.kind!=="tower"||inst.towerId!=="monkey-village")return; const ticks=[0,11,22,33,44,56,67,78,89,100]; ticks.forEach((tick,tickIndex)=>{ const cur=getMonkeyStateAtMoment(inst.id,round,tick); if(!cur.placed||cur.sold||!isUpgradeAtLeast(cur.upgrade,"005"))return; items.push({inst,entry:{towerId:"monkey-village",minUpgrade:"005",dynamic:"monkeyopolis"},entryIndex:`monkeyopolis-${inst.id}`,tickIndex,tick,amount:getMonkeyopolisCrateValue(inst.id,round)}); }); }); }
function isTowerEndIncomeEntry(entry){ return entry.endIncome===true || entry.timing==="end" || entry.tick==="end"; }
function normalizeTowerIncomeTicks(entry){ const raw=entry.ticks??entry.tick??0; const values=Array.isArray(raw)?raw:[raw]; return values.map(v=>clamp(Math.round(Number(v)),0,TICKS_PER_ROUND)).filter(v=>Number.isFinite(v)); }
function getTowerIncomeAmount(entry,index){ const raw=entry.amounts??entry.amount??0; return Number(Array.isArray(raw)?raw[index]??raw[raw.length-1]??0:raw||0); }

function renderCumulative(){ el.cumulativeList.innerHTML=""; for(let r=state.settings.roundStart;r<=state.endRound;r++){ const alive=Object.values(state.monkeyInstances).map(inst=>{const cur=getMonkeyStateAtRound(inst.id,r); if(!cur.placed||cur.sold)return null; const meta=getInstanceMeta(inst,r); return {inst,cur,meta};}).filter(Boolean); const card=document.createElement("div"); card.className="cumulative-round"; card.innerHTML=`<h3>Round ${r}</h3><div class="cumulative-pill-list">${alive.length?alive.map(x=>`<button class="action-chip generated ${x.meta.absorbedVisible?"absorbed":""}" onclick="selectCumulative('${x.inst.id}',${r})">${iconHtml(x.meta.iconKey)}<span>${x.inst.label}</span>${x.cur.upgrade?`<span class="upgrade-code">${x.cur.upgrade}</span>`:""}</button>`).join(""):`<span class="empty-inspector">No towers exist yet.</span>`}</div>`; el.cumulativeList.appendChild(card); } }
window.selectCumulative=function(monkeyId,round){ state.selectedEventId=null; state.selectedCumulative={monkeyId,round}; state.activeRound=round; renderInspector(); renderCumulative(); renderRoundTable(); };
window.selectEvent=function(eventId){ const ev=state.events.find(e=>e.id===eventId); if(ev)state.activeRound=ev.round; state.selectedEventId=eventId; state.selectedCumulative=null; renderInspector(); renderRoundTable(); renderCumulativeIfActive(); };

function renderInspector(){ const ev=state.events.find(e=>e.id===state.selectedEventId); if(state.selectedCumulative){renderCumulativeInspector();return;} if(!ev){el.inspectorContent.className="empty-inspector";el.inspectorContent.innerHTML="Click an action in the Round Map or a tower in Cumulative View.";return;} if(state.inspectorTab==="special")return renderSpecialInspector(ev); if(state.inspectorTab==="buffs")return renderBuffInspector(ev); return renderActionInspector(ev); }
function renderActionInspector(ev){ const inst=ev.monkeyId?state.monkeyInstances[ev.monkeyId]:null; const meta=inst?getInstanceMeta(inst):getHelperMeta(ev); el.inspectorContent.className="inspector-grid"; const isEditableUpgrade=ev.type==="upgrade"||ev.type==="snapshot"; const sellPointActive=!!(inst && state.events.some(e=>e.type==="sell"&&e.monkeyId===inst.id&&e.round===ev.round&&e.id!==ev.id)); const canParagon=ev.type==="upgrade" && !sellPointActive && getTower(ev.towerId)?.paragonAvailable; const paragonReady=canParagon && allT5sExistBefore(ev.towerId,ev.round); const displayUpgrade=ev.upgrade||ev.snapshotUpgrade||"000"; const finalSnapshot=ev.type==="snapshot"&&isFinalUpgrade(displayUpgrade); const upgradeEditor=isEditableUpgrade?`<div class="tier-stack ${sellPointActive||finalSnapshot?"disabled-stack":""}">${tierControlHtml("selected",ev.id,"top",Number(displayUpgrade[0]),canParagon,paragonReady,false,displayUpgrade)}${tierControlHtml("selected",ev.id,"middle",Number(displayUpgrade[1]),canParagon,paragonReady,false,displayUpgrade)}${tierControlHtml("selected",ev.id,"bottom",Number(displayUpgrade[2]),canParagon,paragonReady,false,displayUpgrade)}</div>${finalSnapshot?`<div class="sell-toggle-note">This is the final upgrade snapshot; upgrades are disabled and only sell/delete is available.</div>`:""}`:``; const sellButton=inst?sellButtonHtml(ev,inst,sellPointActive):""; el.inspectorContent.innerHTML=`<div class="inspector-title">${iconHtml(meta.iconKey)}${inst?inst.label:eventLabel(ev,null)}</div><div class="card-meta">${ev.type.toUpperCase()} · Round ${ev.round} · ${ev.source==="generated"?"Generated":"Manual"}${ev.dirty?" · Edited":""}</div>${tickEditorHtml(ev)}<div class="stat-grid"><div class="stat-box"><div class="stat-label">Money Spent</div><div class="stat-value">${inst?formatMoney(calculateTotalSpentOnMonkeyUntilRound(inst.id,ev.round)):"—"}</div></div><div class="stat-box"><div class="stat-label">Money Generated</div><div class="stat-value">${inst?formatMoney(calculateMoneyGeneratedByMonkeyUntilRound(inst.id,ev.round)):"—"}</div></div><div class="stat-box"><div class="stat-label">Sell Value</div><div class="stat-value">${inst?formatMoney(calculateSellValue(inst.id,ev.round)):"—"}</div></div><div class="stat-box"><div class="stat-label">Action Delta</div><div class="stat-value">${formatMoney(getMoneyDelta(ev,ev.round))}</div></div></div>${bankStatsHtml(inst,ev.round,ev.tick)}${sellPointActive?`<div class="sell-toggle-note">Sell mode is on here, so path interactions are dimmed for this action.</div>`:""}${upgradeEditor}${eventSpecificEditor(ev)}<div class="inspector-actions"><button class="danger" onclick="deleteSelectedEvent()">Delete Action</button>${sellButton}</div>`; bindTickEditor(ev); }
function bankStatsHtml(inst,round,tick=TICKS_PER_ROUND){ if(!inst||inst.kind!=="tower")return ""; const cur=getMonkeyStateAtMoment(inst.id,round,tick); if(!isBankUpgrade(inst.towerId,cur.upgrade))return ""; const bank=getBankStateAtMoment(inst.id,round,tick); return `<div class="stat-grid"><div class="stat-box"><div class="stat-label">Bank Money</div><div class="stat-value">${formatMoney(bank.bankMoney)}</div></div><div class="stat-box"><div class="stat-label">Eligable for Interest</div><div class="stat-value">${formatMoney(bank.eligibleInterest)}</div></div><div class="stat-box"><div class="stat-label">Deposited</div><div class="stat-value">${formatMoney(bank.depositedPrincipal)}</div></div></div>`; }
function sellButtonHtml(ev,inst,sellPointActive){ const stateAtEvent=getMonkeyStateAtRound(inst.id,ev.round); const isBasePlacement=["place","place-hero","place-geraldo-item"].includes(ev.type) || (ev.type==="upgrade"&&ev.upgrade==="000"); const isSell=ev.type==="sell"; const disabled=!isSell&&!sellPointActive&&(isBasePlacement||!stateAtEvent.placed||stateAtEvent.sold); const reason=isBasePlacement?"Sell is unavailable on the 000/base placement.":"Sell is unavailable here."; return `<button class="good ${sellPointActive||isSell?"active":""}" ${disabled?`disabled title="${reason}"`:""} onclick="toggleSellHereFromSelected()">${isSell?"Remove Sell Action":sellPointActive?"Undo Sell Here":"Sell Here"}</button>`; }
function tickEditorHtml(ev){ return `<div class="tick-editor"><div class="card-meta"><strong>Action Tick</strong></div><div class="tick-row"><input id="tickSlider" type="range" min="0" max="${TICKS_PER_ROUND}" value="${ev.tick}"><input id="tickText" type="number" min="0" max="${TICKS_PER_ROUND}" value="${ev.tick}"></div></div>`; }
function bindTickEditor(ev){ const s=document.getElementById("tickSlider"), t=document.getElementById("tickText"); if(!s||!t)return; const update=v=>{ const old=ev.tick; ev.tick=clamp(Number(v||0),0,TICKS_PER_ROUND); state.activeRound=ev.round; resetTransientCaches(); const err=validateMonkeyTimeline(ev.monkeyId); if(err){ ev.tick=old; resetTransientCaches(); showToast(err); } else { ev.dirty=true; } s.value=ev.tick; t.value=ev.tick; renderRoundTable(); renderCumulativeIfActive(); }; s.addEventListener("input",()=>update(s.value)); t.addEventListener("change",()=>update(t.value)); }
function eventSpecificEditor(ev){ if(ev.type==="pop-income")return `<div class="mini-form"><label class="input-label">Pop income amount moved to this tick<input id="popAmountInput" type="number" min="0" value="${ev.amount||0}"></label><label class="toggle-row compact-toggle"><span class="toggle-label">Average Split</span><input id="popAverageSplitInput" class="switch-input" type="checkbox" ${ev.averageSplit?"checked":""}><span class="switch-ui"></span></label><p class="card-meta">Average Split spreads this pop income evenly across the round ticks.</p></div>`; if(ev.type==="hero-level")return `<div class="mini-form"><label class="input-label">Money spent to skip levels<input id="heroSpendInput" type="number" min="0" value="${ev.moneySpent||0}"></label></div>`; if(ev.type==="bank-collect")return `<div class="mini-form"><h2>Bank Collect</h2><p class="card-meta">Collect removes all Bank Money and Eligable for Interest from this bank, then adds the Bank Money to global cash.</p></div>`; if(ev.type==="bank-deposit")return `<div class="mini-form"><h2>Bank Deposit</h2><p class="card-meta">Deposit automatically moves half of the bank's remaining storage from global cash into Bank Money. It is not added to Eligable for Interest until round end.</p></div>`; return ""; }
function wireEventSpecificEditor(ev){ const pop=document.getElementById("popAmountInput"); if(pop)pop.addEventListener("input",()=>{ev.amount=Number(pop.value||0);ev.dirty=true;renderRoundTable();}); const split=document.getElementById("popAverageSplitInput"); if(split)split.addEventListener("change",()=>{ev.averageSplit=split.checked;ev.dirty=true;renderRoundTable();renderInspector();}); const hero=document.getElementById("heroSpendInput"); if(hero)hero.addEventListener("input",()=>{ev.moneySpent=Number(hero.value||0);ev.dirty=true;renderRoundTable();}); }
const oldRenderActionInspector=renderActionInspector; renderActionInspector=function(ev){ oldRenderActionInspector(ev); wireEventSpecificEditor(ev); };
function renderCumulativeInspector(){ const {monkeyId,round}=state.selectedCumulative; const inst=state.monkeyInstances[monkeyId]; if(!inst){state.selectedCumulative=null;renderInspector();return;} const meta=getInstanceMeta(inst,round); const cur=getMonkeyStateAtRound(monkeyId,round); el.inspectorContent.className="inspector-grid"; el.inspectorContent.innerHTML=`<div class="inspector-title">${iconHtml(meta.iconKey)}${inst.label}</div><div class="card-meta">Read-only cumulative view · Round ${round}</div><div class="stat-grid"><div class="stat-box"><div class="stat-label">Upgrade</div><div class="stat-value">${cur.upgrade||"—"}</div></div><div class="stat-box"><div class="stat-label">Income</div><div class="stat-value">${formatMoney(calculateMoneyGeneratedByMonkeyUntilRound(monkeyId,round))}</div></div><div class="stat-box"><div class="stat-label">Money Spent</div><div class="stat-value">${formatMoney(calculateTotalSpentOnMonkeyUntilRound(monkeyId,round))}</div></div><div class="stat-box"><div class="stat-label">Sell Value</div><div class="stat-value">${formatMoney(calculateSellValue(monkeyId,round))}</div></div></div>${bankStatsHtml(inst,round,TICKS_PER_ROUND)}<div class="hint-box" style="margin:0;">Cumulative selections are visual only. To edit, select the action chip in the Round Map.</div>`; }

function renderSpecialInspector(ev){ const inst=ev.monkeyId?state.monkeyInstances[ev.monkeyId]:null; if(!inst){el.inspectorContent.className="empty-inspector"; el.inspectorContent.innerHTML="This action has no special menu."; return;} const cur=getMonkeyStateAtRound(inst.id,ev.round); const meta=getInstanceMeta(inst); let html=`<div class="inspector-grid"><div class="inspector-title">${iconHtml(meta.iconKey)}Special actions for ${inst.label}</div><div class="card-meta">Special menus create separate actions. They do not mutate the currently selected action.</div>`;
  if(inst.kind==="tower"){ const t=getTower(inst.towerId); if(isUpgradeAtLeast(cur.upgrade,t.specials?.bankCollectAt)){ const bank=getBankStateAtMoment(inst.id,ev.round,ev.tick); html+=`<div class="mini-form"><h2>Bank</h2><div class="stat-grid"><div class="stat-box"><div class="stat-label">Bank Money</div><div class="stat-value">${formatMoney(bank.bankMoney)}</div></div><div class="stat-box"><div class="stat-label">Eligable for Interest</div><div class="stat-value">${formatMoney(bank.eligibleInterest)}</div></div></div><button onclick="addSpecialAction('${inst.id}','bank-collect')">Add Collect Action</button>${state.settings.monkeyKnowledge&&isUpgradeAtLeast(cur.upgrade,t.specials?.bankDepositAt)?`<button onclick="addSpecialAction('${inst.id}','bank-deposit')">Add Deposit Action</button>`:""}</div>`; } if(isVillageFarmAbsorbUpgrade(cur.upgrade,t)) html+=absorbBoxHtml(inst,"farms","Farm Absorb Interface",cur.upgrade,ev.round); if(isUpgradeAtLeast(cur.upgrade,t.specials?.sunTempleAbsorbAt)||isUpgradeAtLeast(cur.upgrade,t.specials?.trueSunAbsorbAt)) html+=absorbBoxHtml(inst,"all","Sun Temple Absorb Interface"); if(t.abilities?.some(a=>isUpgradeAtLeast(cur.upgrade,a.minUpgrade))) html+=`<div class="mini-form"><h2>Abilities</h2>${t.abilities.filter(a=>isUpgradeAtLeast(cur.upgrade,a.minUpgrade)).map(a=>`<button onclick="addAbilityAction('${inst.id}','${a.id}')">${a.name}</button>`).join("")}</div>`; }
  if(inst.kind==="hero"){ const h=getHero(inst.heroId); html+=`<div class="mini-form"><h2>Hero Leveling</h2><button onclick="addSpecialAction('${inst.id}','hero-level')">Add Skip Level For Money Action</button></div>`; if(h.specials?.adoraAbsorb) html+=absorbBoxHtml(inst,"all","Adora Sacrifice / Absorb Interface"); }
  html+=`</div>`; el.inspectorContent.className="inspector-grid"; el.inspectorContent.innerHTML=html; bindAbsorbDropZones(inst,ev.round); }
function absorbBoxHtml(target,mode,title,currentUpgrade="000",round=MAX_ROUND){ const pending=countPendingVillageFarms(target.id,round); const spent=getVillageAbsorbedFarmSpend(target.id,round); const upgradePrice=getMonkeyopolisUpgradePrice(target.id,currentUpgrade,round); const cratePrice=getMonkeyopolisCrateValue(target.id,round); return `<div class="mini-form"><h2>${title}</h2>${mode==="farms"?`<div class="stat-grid"><div class="stat-box"><div class="stat-label">Farms Absorbed</div><div class="stat-value">${pending}</div></div><div class="stat-box"><div class="stat-label">Absorbed Farm Spend</div><div class="stat-value">${formatMoney(spent)}</div></div><div class="stat-box"><div class="stat-label">Price to Upgrade</div><div class="stat-value">${formatMoney(upgradePrice)}</div></div><div class="stat-box"><div class="stat-label">Price of Crate</div><div class="stat-value">${formatMoney(cratePrice)}</div></div></div><button class="good" ${pending<1?`disabled title="Absorb at least one farm first."`:""} onclick="upgradeMonkeyopolis('${target.id}')">Upgrade</button>`:""}<div class="drop-zone" data-absorb-target="${target.id}" data-absorb-mode="${mode}">Drag existing towers here to create a separate absorb action.</div><div class="card-meta">Village farms stay pending for Monkeyopolis; tier 5 and already absorbed farms are blocked.</div></div>`; }
function bindAbsorbDropZones(target,round){ document.querySelectorAll("[data-absorb-target]").forEach(zone=>{ zone.addEventListener("dragover",ev=>{ev.preventDefault();zone.classList.add("drop-hover")}); zone.addEventListener("dragleave",()=>zone.classList.remove("drop-hover")); zone.addEventListener("drop",ev=>{ev.preventDefault();zone.classList.remove("drop-hover"); const p=JSON.parse(ev.dataTransfer.getData("text/plain")||"{}"); if(p.type!=="existing-monkey"){showToast("Drop an existing monkey here.");return;} addAbsorbAction(target.id,p.monkeyId,round,zone.dataset.absorbMode); }); }); }
function renderBuffInspector(ev){ const inst=ev.monkeyId?state.monkeyInstances[ev.monkeyId]:null; if(!inst){el.inspectorContent.className="empty-inspector";el.inspectorContent.innerHTML="This action has no buff target.";return;} const buffs=getBuffsForMonkey(inst.id); el.inspectorContent.className="inspector-grid"; el.inspectorContent.innerHTML=`<div class="inspector-title">${iconHtml(getInstanceMeta(inst).iconKey)}Buffs for ${inst.label}</div><div class="drop-zone" id="buffDropZone">Drop existing monkey here as buff source</div><div class="buff-list">${buffs.length?buffs.map(buffCardHtml).join(""):`<div class="empty-inspector">No buffs assigned yet.</div>`}</div>`; bindBuffDropZone(inst.id); }
function buffCardHtml(buff){ const src=state.monkeyInstances[buff.sourceMonkeyId]; return `<div class="buff-card"><div class="card-title">${src?iconHtml(getInstanceMeta(src).iconKey):""}<span>${src?src.label:"Missing"}</span></div><div class="card-meta">Type: ${buff.type}</div><div class="inspector-actions"><button class="danger" onclick="removeBuff('${buff.id}')">Remove Buff</button></div></div>`; }
function bindBuffDropZone(targetMonkeyId){ const z=document.getElementById("buffDropZone"); if(!z)return; z.addEventListener("dragover",ev=>{ev.preventDefault();z.classList.add("drop-hover")}); z.addEventListener("dragleave",()=>z.classList.remove("drop-hover")); z.addEventListener("drop",ev=>{ev.preventDefault();z.classList.remove("drop-hover"); const p=JSON.parse(ev.dataTransfer.getData("text/plain")||"{}"); if(p.type!=="existing-monkey"){showToast("Drop an existing monkey.");return;} if(p.monkeyId===targetMonkeyId){showToast("A monkey cannot buff itself here.");return;} state.buffs.push({id:makeId("buff",state.nextBuffNumber++),targetMonkeyId,sourceMonkeyId:p.monkeyId,type:"income-buff",multiplier:1,flatBonus:0}); renderAll(); }); }
window.removeBuff=id=>{state.buffs=state.buffs.filter(b=>b.id!==id);renderAll();};

window.addSpecialAction=function(monkeyId,type){ const inst=state.monkeyInstances[monkeyId]; const selected=state.events.find(e=>e.id===state.selectedEventId); const round=selected?.round||state.settings.roundStart; const data={monkeyId,round,type,source:"manual",amount:0}; if(type==="hero-level")data.heroId=inst.heroId; else data.towerId=inst.towerId; const ev=makeEvent(data); state.events.push(ev); state.selectedEventId=ev.id; state.inspectorTab="action"; document.querySelectorAll("[data-inspector-tab]").forEach(o=>o.classList.toggle("active",o.dataset.inspectorTab==="action")); renderAll(); };
window.addAbilityAction=function(monkeyId,abilityId){ const inst=state.monkeyInstances[monkeyId]; const selected=state.events.find(e=>e.id===state.selectedEventId); const ev=makeEvent({monkeyId,towerId:inst.towerId,round:selected?.round||state.settings.roundStart,type:"ability",abilityId,source:"manual"}); state.events.push(ev); state.selectedEventId=ev.id; renderAll(); };
function addAbsorbAction(targetMonkeyId,sourceMonkeyId,round,mode){ if(targetMonkeyId===sourceMonkeyId){showToast("Target cannot absorb itself.");return;} const target=state.monkeyInstances[targetMonkeyId], source=state.monkeyInstances[sourceMonkeyId]; if(!target||!source)return; if(source.absorbedBy){showToast("This farm is already absorbed or pending absorption.");return;} const sourceState=getMonkeyStateAtRound(sourceMonkeyId,round); if(mode==="farms"){ const targetState=getMonkeyStateAtRound(targetMonkeyId,round); if(target.towerId!=="monkey-village"||!isVillageFarmAbsorbUpgrade(targetState.upgrade,getTower(target.towerId))){showToast("Only xx4 villages can absorb farms.");return;} if(source.towerId!=="banana-farm"){showToast("This absorb interface only accepts farms.");return;} if(isFinalUpgrade(sourceState.upgrade)){showToast("Tier 5 farms cannot be absorbed.");return;} } const ev=makeEvent({monkeyId:targetMonkeyId,towerId:target.towerId,heroId:target.heroId,round,type:"absorb",source:"manual",absorbedMonkeyIds:[sourceMonkeyId],absorbMode:mode,absorbedMoneySpent:calculateTotalSpentOnMonkeyUntilRound(sourceMonkeyId,round)}); state.events.push(ev); markAbsorbed(sourceMonkeyId,ev.id,mode==="farms"?"pending-village":"absorb",round); state.selectedEventId=ev.id; refreshVillageAbsorbTotals(); renderAll(); }
window.createParagonFromSelected=function(eventId){ const ev=state.events.find(e=>e.id===eventId); if(!ev)return; const t=getTower(ev.towerId); if(!t?.paragonAvailable||!allT5sExistBefore(t.id,ev.round)){showToast("Paragon requires all T5 paths before this action.");return;} const absorbed=Object.values(state.monkeyInstances).filter(i=>i.towerId===t.id && !getMonkeyStateAtRound(i.id,ev.round).sold).map(i=>i.id); const paragonId=makeId("monkey",state.nextMonkeyNumber++); const pIndex=state.nextParagonNumber++; state.monkeyInstances[paragonId]={id:paragonId,towerId:t.id,label:`${t.paragonName||t.name+" Paragon"} #${pIndex}`,kind:"paragon",paragonOf:t.id,paragonIndex:pIndex}; const pEvent=makeEvent({monkeyId:paragonId,towerId:t.id,round:ev.round,type:"paragon",source:"manual",cost:0,absorbedMonkeyIds:absorbed,paragonIndex:pIndex}); state.events.push(pEvent); absorbed.forEach(id=>markAbsorbed(id,pEvent.id,"paragon",ev.round,pIndex)); state.selectedEventId=pEvent.id; renderAll(); };
function markAbsorbed(monkeyId,eventId,kind,round,index=null){ const inst=state.monkeyInstances[monkeyId]; if(!inst)return; inst.absorbedBy=eventId; inst.absorbedKind=kind; inst.absorbedRound=round; inst.absorbedParagonIndex=index; state.paragonHistory[monkeyId]=state.paragonHistory[monkeyId]||[]; state.paragonHistory[monkeyId].push({eventId,kind,round,index}); }

window.addSellActionFromSelected=function(){ return toggleSellHereFromSelected(); };
window.toggleSellHereFromSelected=function(){
  const ev=state.events.find(e=>e.id===state.selectedEventId); if(!ev||!ev.monkeyId)return;
  if(ev.type==="sell"){ state.events=state.events.filter(e=>e.id!==ev.id); state.selectedEventId=null; renderAll(); return; }
  const inst=state.monkeyInstances[ev.monkeyId];
  const stateAtEvent=getMonkeyStateAtRound(inst.id,ev.round);
  if(["place","place-hero","place-geraldo-item"].includes(ev.type)||(ev.type==="upgrade"&&ev.upgrade==="000")||!stateAtEvent.placed||stateAtEvent.sold){ showToast("Sell is unavailable on the 000/base placement."); return; }
  const existing=state.events.find(e=>e.type==="sell"&&e.monkeyId===ev.monkeyId&&e.round===ev.round&&e.id!==ev.id); if(existing){ state.events=state.events.filter(e=>e.id!==existing.id); state.selectedEventId=ev.id; renderAll(); return; }
  const timeline=getMonkeyTimeline(ev.monkeyId);
  if(timeline[timeline.length-1]?.id!==ev.id){ showToast("Sell can only convert the final action for this monkey."); return; }
  const before={type:ev.type,snapshotUpgrade:ev.snapshotUpgrade,upgrade:ev.upgrade,fromUpgrade:ev.fromUpgrade,towerId:ev.towerId,heroId:ev.heroId,itemId:ev.itemId,moneySpent:ev.moneySpent,amount:ev.amount,cost:ev.cost,absorbedMonkeyIds:ev.absorbedMonkeyIds};
  ev.type="sell"; delete ev.snapshotUpgrade; delete ev.upgrade; delete ev.fromUpgrade; delete ev.moneySpent; delete ev.amount; delete ev.cost; delete ev.absorbedMonkeyIds;
  resetTransientCaches();
  const err=validateMonkeyTimeline(ev.monkeyId); if(err){ Object.assign(ev,before); resetTransientCaches(); showToast(err); return; }
  ev.dirty=true; state.selectedEventId=ev.id; state.activeRound=ev.round; renderAll();
};
window.deleteSelectedEvent=function(){ const ev=state.events.find(e=>e.id===state.selectedEventId); if(!ev)return; deleteEventById(ev.id); state.selectedEventId=null; renderAll(); };

function sanitizePlanForRules(){
  for(const inst of Object.values({...state.monkeyInstances})){ if(inst.kind==="tower"){ const t=getTower(inst.towerId); if(!t || !t.enabled){ removeMonkey(inst.id); } } }
  state.events.forEach(ev=>{ if(ev.type==="upgrade"){ const t=getTower(ev.towerId); const clamped=clampUpgradeToRules(ev.upgrade,t); if(clamped!==ev.upgrade){ev.upgrade=clamped;ev.dirty=true;} } });
  enforceUniqueT5s(); cleanupInvalidTimelines(); cleanupOrphans();
}
function clampUpgradeToRules(up,t){ let d=up.split("").map(Number); PATH_KEYS.forEach(path=>{d[PATH_INDEX[path]]=clamp(d[PATH_INDEX[path]],0,t.maxPathTiers[path]??5);}); let next=d.join(""); while(!isUpgradePatternAllowed(next,t)){ const nums=next.split("").map(Number); const idx=nums.indexOf(Math.max(...nums)); nums[idx]=Math.max(0,nums[idx]-1); next=nums.join(""); } return next; }
function enforceUniqueT5s(){ const seen={}; state.events.filter(e=>e.type==="upgrade").sort((a,b)=>a.round-b.round||compareEvents(a,b)).forEach(ev=>{ const t=getTower(ev.towerId); const d=ev.upgrade.split("").map(Number); d.forEach((tier,idx)=>{ if(tier===5){ const key=`${ev.towerId}-${idx}`; seen[key]=seen[key]||new Set(); const limit=getT5Limit(ev.towerId,idx); if(!seen[key].has(ev.monkeyId) && seen[key].size>=limit){ d[idx]=4; ev.upgrade=d.join(""); ev.dirty=true; showToast("Duplicate T5 path was lowered to tier 4 by rules."); return; } seen[key].add(ev.monkeyId); } }); }); }
function getT5Limit(towerId,pathIdx){ let limit=clamp(Number(state.settings.players||1),1,4); if(towerId==="dart-monkey"&&pathIdx===2&&(state.settings.monkeyKnowledge||state.settings.selectedHero==="silas"))limit=Math.max(limit,2); return limit; }
function removeMonkey(id){ releaseAbsorbedByMonkey(id); releaseAbsorbedMarker(id); delete state.monkeyInstances[id]; state.events=state.events.filter(e=>e.monkeyId!==id); state.buffs=state.buffs.filter(b=>b.targetMonkeyId!==id&&b.sourceMonkeyId!==id); refreshVillageAbsorbTotals(); }
function cleanupOrphans(){ state.events=state.events.filter(e=>!e.monkeyId || state.monkeyInstances[e.monkeyId]); }
function cleanupInvalidTimelines(){ Object.keys(state.monkeyInstances).forEach(id=>{ const err=validateMonkeyTimeline(id); if(err){ state.events.filter(e=>e.monkeyId===id&&e.type!=="place"&&e.type!=="place-hero"&&e.type!=="place-geraldo-item").forEach(e=>e.dirty=true); } }); }
function sanitizeHeroesForSelection(){ Object.values(state.monkeyInstances).forEach(inst=>{ if(inst.kind==="hero"&&inst.heroId!==state.settings.selectedHero)removeMonkey(inst.id); }); if(state.settings.selectedHero!=="geraldo") Object.values(state.monkeyInstances).forEach(inst=>{ if(inst.kind==="geraldo-item")removeMonkey(inst.id); }); }
function removeEventsBeforeRoundStart(){ const before=state.settings.roundStart; const affected=new Set(state.events.filter(e=>e.round<before&&e.monkeyId).map(e=>e.monkeyId)); state.events=state.events.filter(e=>e.round>=before); affected.forEach(id=>{ if(!state.events.some(e=>e.monkeyId===id)) delete state.monkeyInstances[id]; }); cleanupOrphans(); }

function runCalculator(){ clearGeneratedCalculatorActions(); const id=placeNewTower("banana-farm",state.settings.roundStart,"generated"); if(id){ const ev=state.events.find(e=>e.monkeyId===id&&e.type==="place"); if(ev){ ev.source="generated"; ev.tick=0; state.selectedEventId=ev.id; } } renderAll(); showToast("Calculate added an editable generated 000 farm at the earliest round."); }
function clearGeneratedCalculatorActions(){ const generatedPlacements=new Set(state.events.filter(e=>e.source==="generated"&&["place","place-hero","place-geraldo-item","paragon"].includes(e.type)&&e.monkeyId).map(e=>e.monkeyId)); generatedPlacements.forEach(id=>removeMonkey(id)); state.events=state.events.filter(e=>e.source!=="generated"); cleanupOrphans(); }
function clearAllPlan(){ state.events=[]; state.monkeyInstances={}; state.buffs=[]; state.paragonHistory={}; state.selectedEventId=null; state.selectedCumulative=null; state.roundMoneyTicks={}; state.activeRound=state.settings.roundStart; state.nextEventNumber=1; state.nextMonkeyNumber=1; state.nextBuffNumber=1; state.nextParagonNumber=1; renderAll(); showToast("Cleared all planner actions."); }


function bindDragToDelete(){ document.addEventListener("dragover",ev=>{ const raw=ev.dataTransfer?.types?.includes("text/plain"); if(raw)ev.preventDefault(); }); document.addEventListener("drop",ev=>{ const raw=ev.dataTransfer?.getData("text/plain"); if(!raw)return; let p={}; try{p=JSON.parse(raw);}catch{return;} if(p.type!=="event-action")return; if(ev.target.closest(".round-row")||ev.target.closest("[data-absorb-target]")||ev.target.closest("#buffDropZone"))return; ev.preventDefault(); deleteEventById(p.eventId); state.selectedEventId=null; renderAll(); showToast("Dragged action out of the round editor and deleted it."); }); }
function deleteEventById(eventId){ const ev=state.events.find(e=>e.id===eventId); if(!ev)return; if(ev.type==="place"||ev.type==="place-hero"||ev.type==="place-geraldo-item"||ev.type==="paragon"){ removeMonkey(ev.monkeyId); } else { if(ev.type==="absorb")releaseAbsorbedByEvent(ev.id); state.events=state.events.filter(e=>e.id!==ev.id); } refreshVillageAbsorbTotals(); }
function cloneBankState(bankState={}){ return Object.fromEntries(Object.entries(bankState||{}).map(([id,b])=>[id,{bankMoney:Number(b.bankMoney||0),eligibleInterest:Number(b.eligibleInterest||0),depositedPrincipal:Number(b.depositedPrincipal||0)}])); }
function isBankUpgrade(towerId,upgrade){ return towerId==="banana-farm"&&Number(String(upgrade||"000")[1]||0)>=3; }
function getBankCapacity(upgrade){ const middle=Number(String(upgrade||"000")[1]||0); if(middle>=4)return 10000; if(middle>=3)return 7000; return 0; }
function getBankInterestRate(){ return .15; }
function ensureBankState(bankState,monkeyId){ bankState[monkeyId]=bankState[monkeyId]||{bankMoney:0,eligibleInterest:0,depositedPrincipal:0}; return bankState[monkeyId]; }
function clampBankAccount(account,capacity){ account.bankMoney=clamp(Math.floor(Number(account.bankMoney||0)),0,capacity); account.eligibleInterest=clamp(Math.floor(Number(account.eligibleInterest||0)),0,capacity); account.depositedPrincipal=clamp(Math.floor(Number(account.depositedPrincipal||0)),0,account.bankMoney); }
function applyBankEvent(ev,round,bankState,money){ const cur=ev.monkeyId?getMonkeyStateAtMoment(ev.monkeyId,round,ev.tick):null; const bankActive=cur&&isBankUpgrade(ev.towerId,cur.upgrade); if(ev.type==="tower-income"&&ev.bankIncome&&bankActive){ const account=ensureBankState(bankState,ev.monkeyId); const cap=getBankCapacity(cur.upgrade); account.bankMoney+=Number(ev.amount||0); account.eligibleInterest+=Number(ev.amount||0); clampBankAccount(account,cap); return {money,conflict:false,incomeDelta:Number(ev.amount||0)}; } if(ev.type==="bank-collect"&&bankActive){ const account=ensureBankState(bankState,ev.monkeyId); const collected=account.bankMoney; const incomeDelta=Math.max(0,collected-Number(account.depositedPrincipal||0)); account.bankMoney=0; account.eligibleInterest=0; account.depositedPrincipal=0; return {money:money+collected,conflict:false,incomeDelta}; } if(ev.type==="bank-deposit"&&bankActive){ const account=ensureBankState(bankState,ev.monkeyId); const cap=getBankCapacity(cur.upgrade); const deposit=Math.min(5000,Math.max(0,cap-account.bankMoney)); const conflict=money<deposit; account.bankMoney+=deposit; account.depositedPrincipal+=deposit; clampBankAccount(account,cap); return {money:money-deposit,conflict,incomeDelta:0}; } return null; }
function applyEndOfRoundBankInterest(round,bankState){ let income=0; Object.values(state.monkeyInstances).forEach(inst=>{ if(inst.kind!=="tower")return; const cur=getMonkeyStateAtMoment(inst.id,round,TICKS_PER_ROUND); if(!cur.placed||cur.sold||!isBankUpgrade(inst.towerId,cur.upgrade))return; const account=ensureBankState(bankState,inst.id); const cap=getBankCapacity(cur.upgrade); const before=account.bankMoney; const interest=Math.floor(account.eligibleInterest*getBankInterestRate()); account.bankMoney+=interest; account.eligibleInterest+=interest; clampBankAccount(account,cap); income+=Math.max(0,account.bankMoney-before); if(Number(cur.upgrade[1])>=4)account.eligibleInterest=account.bankMoney; }); return income; }
function getBankStateAtMoment(monkeyId,round,tick=TICKS_PER_ROUND){ let money=Number(state.settings.startingCash||0), bankState={}; for(let r=state.settings.roundStart;r<=round;r++){ const result=simulateRoundMoney(r,money,r===round?tick:null,r!==round,bankState); money=result.money; bankState=result.bankState; } return cloneBankState(bankState)[monkeyId]||{bankMoney:0,eligibleInterest:0,depositedPrincipal:0}; }
function getBankActionDeltaAtEvent(ev){ const before=getBankStateAtMoment(ev.monkeyId,ev.round,Math.max(0,ev.tick-1)); const cur=getMonkeyStateAtMoment(ev.monkeyId,ev.round,ev.tick); if(!isBankUpgrade(ev.towerId,cur.upgrade))return 0; if(ev.type==="bank-collect")return before.bankMoney; if(ev.type==="bank-deposit")return -Math.min(5000,Math.max(0,getBankCapacity(cur.upgrade)-before.bankMoney)); return 0; }
function calculateUpgradeCostForEvent(ev){ const from=ev.fromUpgrade||getPreviousUpgradeBefore(ev); const base=calculateUpgradeCostDelta(ev.towerId,from,ev.upgrade); if(ev.towerId==="monkey-village"&&Number(from[2]||0)<5&&Number(ev.upgrade[2]||0)>=5)return base+getMonkeyopolisFarmUpgradeCost(ev.monkeyId,ev.round); return base; }
function isVillageFarmAbsorbUpgrade(up,tower){ return tower?.id==="monkey-village"&&Number(String(up||"000")[2]||0)===4; }
function countPendingVillageFarms(villageId,throughRound=MAX_ROUND){ return state.events.filter(e=>e.type==="absorb"&&e.monkeyId===villageId&&e.absorbMode==="farms"&&e.round<=throughRound).reduce((sum,e)=>sum+(e.absorbedMonkeyIds?.length||0),0); }
function isVillage005UpgradeBlocked(ev,next){ if(ev.towerId!=="monkey-village")return false; const cur=ev.upgrade||ev.snapshotUpgrade||"000"; return Number(cur[2]||0)<5&&Number(next[2]||0)>=5; }
function isVillageBottomDowngradeLocked(ev,path,current){ return ev.towerId==="monkey-village"&&path==="bottom"&&Number(String(current||"000")[2]||0)>=4; }
function selectedTierDecreaseLocked(id,path){ const ev=state.events.find(e=>e.id===id); const current=ev?.upgrade||ev?.snapshotUpgrade||"000"; return !!ev&&isVillageBottomDowngradeLocked(ev,path,current); }
function selectedTierIncreaseLocked(id,path){ const ev=state.events.find(e=>e.id===id); const current=ev?.upgrade||ev?.snapshotUpgrade||"000"; return !!ev&&ev.towerId==="monkey-village"&&path==="bottom"&&Number(String(current||"000")[2]||0)===4; }
function refreshVillageAbsorbTotals(){ Object.values(state.monkeyInstances).forEach(inst=>{ if(inst.towerId==="monkey-village"){ const absorbs=state.events.filter(e=>e.type==="absorb"&&e.monkeyId===inst.id&&e.absorbMode==="farms"); absorbs.forEach(e=>{ e.absorbedMoneySpent=(e.absorbedMonkeyIds||[]).reduce((sum,id)=>sum+calculateTotalSpentOnMonkeyUntilRound(id,e.round),0); }); inst.absorbedFarmMoneySpent=absorbs.reduce((sum,e)=>sum+Number(e.absorbedMoneySpent||0),0); } }); }
function releaseAbsorbedByEvent(eventId){ Object.values(state.monkeyInstances).forEach(inst=>{ if(inst.absorbedBy===eventId)releaseAbsorbedMarker(inst.id); }); }
function releaseAbsorbedByMonkey(monkeyId){ state.events.filter(e=>e.monkeyId===monkeyId&&e.absorbedMonkeyIds).forEach(e=>releaseAbsorbedByEvent(e.id)); }
function releaseAbsorbedMarker(monkeyId){ const inst=state.monkeyInstances[monkeyId]; if(!inst)return; delete inst.absorbedBy; delete inst.absorbedKind; delete inst.absorbedRound; delete inst.absorbedParagonIndex; delete inst.absorbedPending; delete state.paragonHistory[monkeyId]; }

function getMonkeyopolisFarmUpgradeCost(villageId,round=MAX_ROUND){ return countPendingVillageFarms(villageId,round)*priceWithDifficulty(5000); }
function getMonkeyopolisUpgradePrice(villageId,currentUpgrade="000",round=MAX_ROUND){ const next=getMonkeyopolisUpgradeCode(currentUpgrade); return calculateUpgradeCostDelta("monkey-village",currentUpgrade,next)+getMonkeyopolisFarmUpgradeCost(villageId,round); }
function getMonkeyopolisUpgradeCode(currentUpgrade="000"){ const nums=upgradeNums(currentUpgrade); nums[2]=5; return nums.join(""); }
function getVillageAbsorbedFarmSpend(villageId,round=MAX_ROUND){ return state.events.filter(e=>e.type==="absorb"&&e.monkeyId===villageId&&e.absorbMode==="farms"&&e.round<=round).reduce((sum,e)=>sum+Number(e.absorbedMoneySpent||0),0); }
function getMonkeyopolisExtraIncome(villageId,round=MAX_ROUND){ const spent=getVillageAbsorbedFarmSpend(villageId,round); return Math.floor(spent/2000)*200; }
function getMonkeyopolisCrateValue(villageId,round=MAX_ROUND){ return Math.floor((1000+getMonkeyopolisExtraIncome(villageId,round))/10); }
window.upgradeMonkeyopolis=function(villageId){ const inst=state.monkeyInstances[villageId]; if(!inst||inst.towerId!=="monkey-village")return; const selected=state.events.find(e=>e.id===state.selectedEventId); const round=selected?.round||state.settings.roundStart; const cur=getMonkeyStateAtRound(villageId,round); if(!cur.placed||cur.sold){ showToast("Monkeyopolis upgrade needs a live village."); return; } if(countPendingVillageFarms(villageId,round)<1){ showToast("Absorb at least one farm first."); return; } const next=getMonkeyopolisUpgradeCode(cur.upgrade||"000"); if(Number(String(cur.upgrade||"000")[2]||0)>=5){ showToast("This village is already Monkeyopolis."); return; } const ev=makeEvent({monkeyId:villageId,towerId:inst.towerId,round,type:"upgrade",fromUpgrade:cur.upgrade||"000",upgrade:next,source:"manual"}); state.events.push(ev); state.activeRound=round; resetTransientCaches(); const err=validateMonkeyTimeline(villageId); if(err){ state.events=state.events.filter(e=>e.id!==ev.id); resetTransientCaches(); showToast(err); return; } state.selectedEventId=ev.id; state.inspectorTab="action"; document.querySelectorAll("[data-inspector-tab]").forEach(o=>o.classList.toggle("active",o.dataset.inspectorTab==="action")); renderAll(); };
function getGameDifficultyPriceMultiplier(){ return ({Easy:.85,Medium:1,Hard:1.08,Impoppable:1.2,CHIMPS:1.08})[state.settings.gameDifficulty]||1; }
function roundToNearestFive(value){ return Math.round(Number(value||0)/5)*5; }
function priceWithDifficulty(price){ return roundToNearestFive(Number(price||0)*getGameDifficultyPriceMultiplier()); }
function isFinalUpgrade(up){ return String(up||"000").split("").some(v=>v==="5"); }
function upgradeNums(up){ return String(up||"000").split("").map(Number); }
function isUpgradeGreaterOrEqual(next,prev){ const n=upgradeNums(next), p=upgradeNums(prev); return n.every((v,i)=>v>=p[i]); }
function isUpgradeStrictlyGreater(next,prev){ const n=upgradeNums(next), p=upgradeNums(prev); return isUpgradeGreaterOrEqual(next,prev)&&n.some((v,i)=>v>p[i]); }
function getMonkeyTimeline(monkeyId){ if(state.monkeyTimelineCache?.has(monkeyId))return state.monkeyTimelineCache.get(monkeyId); const timeline=state.events.filter(e=>e.monkeyId===monkeyId).sort((a,b)=>a.round-b.round||compareEvents(a,b)); state.monkeyTimelineCache?.set(monkeyId,timeline); return timeline; }
function getPreviousUpgradeBefore(ev){ if(!ev?.monkeyId)return "000"; let up="000"; for(const item of getMonkeyTimeline(ev.monkeyId)){ if(item.id===ev.id)break; if(item.type==="upgrade")up=item.upgrade; if(item.type==="paragon")up="PARAGON"; } return up; }
function validateMonkeyTimeline(monkeyId){ if(!monkeyId)return null; const inst=state.monkeyInstances[monkeyId]; if(!inst)return null; const timeline=getMonkeyTimeline(monkeyId); let placed=false, highest="000", sold=false; for(let i=0;i<timeline.length;i++){ const ev=timeline[i]; if(sold)return "Sell must be the last action for that monkey."; if(["place","place-hero","place-geraldo-item","paragon"].includes(ev.type)){ if(placed&&ev.type==="place")return "Base tower placement cannot be after upgrades."; placed=true; if(ev.type==="paragon")highest="PARAGON"; continue; } if(!placed&&["snapshot","upgrade","sell"].includes(ev.type))return "Action cannot be before that monkey is placed."; if(ev.type==="snapshot"){ const snap=ev.snapshotUpgrade||highest; if(!isUpgradeGreaterOrEqual(snap,highest))return "Nontransformative tower cannot be lower than previous upgrades."; ev.snapshotUpgrade=highest; continue; } if(ev.type==="upgrade"){ if(highest==="PARAGON")return "Cannot upgrade after final paragon upgrade."; if(!isUpgradeStrictlyGreater(ev.upgrade,highest))return "Cannot move or lower an upgrade after a larger upgrade."; if(ev.towerId==="monkey-village"&&Number(highest[2]||0)<5&&Number(ev.upgrade[2]||0)>=5&&countPendingVillageFarms(ev.monkeyId,ev.round)<1)return "Monkeyopolis requires at least one pending absorbed farm."; highest=ev.upgrade; continue; } if(ev.type==="sell"){ sold=true; if(i!==timeline.length-1)return "Sell must be the last action for that monkey."; } } return null; }
function getMonkeyStateAtRound(monkeyId,round){ const key=`${monkeyId}|${round}`; if(state.monkeyStateRoundCache?.has(key))return state.monkeyStateRoundCache.get(key); let placed=false,upgrade="000",sold=false; for(const ev of getMonkeyTimeline(monkeyId)){ if(ev.round>round)break; if(["place","place-hero","place-geraldo-item","paragon"].includes(ev.type)){placed=true;sold=false;if(ev.type==="paragon")upgrade="PARAGON";} if(ev.type==="upgrade"&&placed&&!sold)upgrade=ev.upgrade; if(ev.type==="sell"&&placed)sold=true; } const result={placed,upgrade,sold}; state.monkeyStateRoundCache?.set(key,result); return result; }

function getMonkeyStateAtMoment(monkeyId,round,tick){ const key=`${monkeyId}|${round}|${tick}`; if(state.monkeyStateMomentCache?.has(key))return state.monkeyStateMomentCache.get(key); let placed=false,upgrade="000",sold=false; for(const ev of getMonkeyTimeline(monkeyId)){ if(ev.round>round||(ev.round===round&&ev.tick>tick))break; if(["place","place-hero","place-geraldo-item","paragon"].includes(ev.type)){placed=true;sold=false;if(ev.type==="paragon")upgrade="PARAGON";} if(ev.type==="upgrade"&&placed&&!sold)upgrade=ev.upgrade; if(ev.type==="sell"&&placed)sold=true; } const result={placed,upgrade,sold}; state.monkeyStateMomentCache?.set(key,result); return result; }
function getNextAvailableUpgrade(current,tower,monkeyId,round){ for(const path of PATH_KEYS){ const next=addOneTier(current,path); if(next&&isUpgradePatternAllowed(next,tower)&&wouldNotBreakT5Limit(tower.id,next,monkeyId,round))return next; } return null; }
function addOneTier(up,path){ const d=up.split("").map(Number); const i=PATH_INDEX[path]; if(d[i]>=5)return null; d[i]++; return d.join(""); }
function changeUpgradeTier(up,path,delta){ if(delta>0&&deltaWouldLockCrosspath(up,path,delta))return null; const d=up.split("").map(Number); const i=PATH_INDEX[path]; d[i]+=delta; if(d[i]<0||d[i]>5)return null; return d.join(""); }
function deltaWouldLockCrosspath(up,path,delta){ if(!up||delta<=0)return false; const d=up.split("").map(Number); const i=PATH_INDEX[path]; if(d[i]>0)return false; return d.filter(v=>v>0).length>=2; }
function isUpgradePatternAllowed(up,tower){ const d=up.split("").map(Number); if(d.some(v=>v<0||v>5))return false; if(tower){ for(const p of PATH_KEYS){ if(d[PATH_INDEX[p]]>(tower.maxPathTiers[p]??5))return false; } } const above=d.filter(v=>v>2).length, nonzero=d.filter(v=>v>0).length; if(nonzero>2)return false; if(above>1)return false; return true; }
function wouldNotBreakT5Limit(towerId,up,monkeyId,round){ const d=up.split("").map(Number); for(let i=0;i<3;i++){ if(d[i]===5){ const existing=countT5s(towerId,i,round,monkeyId); if(existing>=getT5Limit(towerId,i))return false; } } return true; }
function countT5s(towerId,pathIdx,round,excludeMonkeyId=null){ return Object.values(state.monkeyInstances).filter(inst=>inst.towerId===towerId&&inst.id!==excludeMonkeyId).filter(inst=>{ const cur=getMonkeyStateAtRound(inst.id,round); return !cur.sold && cur.upgrade?.[pathIdx]==="5"; }).length; }
function allT5sExistBefore(towerId,round){ return [0,1,2].every(i=>countT5s(towerId,i,round,null)>=1); }
function isUpgradeAtLeast(up,min){ if(!min)return false; const d=up.split("").map(Number), m=min.split("").map(Number); return d.some((v,i)=>v>=m[i]&&m[i]>0); }
function hasAnyAvailablePath(t){ return t.enabled&&PATH_KEYS.some(p=>(t.maxPathTiers[p]??0)>0); }
function wouldBreakTowerLimits(towerId){ const total=countTowerLimitOccupants(); if(total>=state.settings.maxTowers)return true; if(towerId==="banana-farm"&&countExistingTower("banana-farm")>=state.settings.maxBananaFarms)return true; if(towerId==="monkey-buccaneer"&&isBoatPlacementUnavailable())return true; return false; }
function isBoatPlacementUnavailable(){ return getBoatSpotLimit()<=0 || countExistingTower("monkey-buccaneer")>=getBoatSpotLimit(); }
function getBoatSpotLimit(){ return getMapBoatSpotLimit()+getLordOfAbyssBoatSpotLimit(); }
function getMapBoatSpotLimit(){ return Math.max(0,Number(state.settings.maxBoatSpots||0)); }
function getLordOfAbyssBoatSpotLimit(){ return Math.max(0,Number(state.settings.lordOfAbyss||0)); }
function countExistingTower(towerId){ return Object.values(state.monkeyInstances).filter(i=>i.towerId===towerId).length; }
function countTowerLimitOccupants(){ return Object.values(state.monkeyInstances).filter(i=>i.kind==="tower"||i.kind==="hero").length; }
function hasHeroPlaced(heroId){ return Object.values(state.monkeyInstances).some(i=>i.kind==="hero"&&i.heroId===heroId); }
function isExistingDragDisabled(inst,round){ if(!inst.absorbedBy)return false; const paragonOrAbsorb=state.events.find(e=>e.id===inst.absorbedBy); const sold=paragonOrAbsorb && state.events.some(e=>e.monkeyId===paragonOrAbsorb.monkeyId&&e.type==="sell"&&e.round<=round); if(inst.absorbedKind==="pending-village"){ const villageState=paragonOrAbsorb?getMonkeyStateAtRound(paragonOrAbsorb.monkeyId,round):null; return !sold && inst.absorbedRound<=round && Number(villageState?.upgrade?.[2]||0)>=5; } return !sold && inst.absorbedRound<=round; }
function calculateSellValue(monkeyId,round,tick=TICKS_PER_ROUND){ const inst=state.monkeyInstances[monkeyId]; if(!inst)return 0; const rate=inst.kind==="tower"?getTower(inst.towerId).sellbackRate:.70; return Math.floor(calculateTotalSpentOnMonkeyUntilRound(monkeyId,round)*rate)+getBankStateAtMoment(monkeyId,round,tick).bankMoney; }
function calculateTotalSpentOnMonkeyUntilRound(monkeyId,round){ return state.events.filter(e=>e.monkeyId===monkeyId&&e.round<=round&&e.type!=="sell").reduce((s,e)=>s+Math.max(0,-getMoneyDelta(e,e.round)),0); }
function calculateMoneyGeneratedByMonkeyUntilRound(monkeyId,round){ const manual=state.events.filter(e=>e.monkeyId===monkeyId&&e.round<=round).reduce((s,e)=>s+Math.max(0,getMoneyDelta(e,e.round)),0); const towerIncome=Array.from({length:Math.max(0,round-state.settings.roundStart+1)},(_,i)=>state.settings.roundStart+i).reduce((sum,r)=>sum+getTowerIncomeForRound(r).filter(item=>item.inst.id===monkeyId).reduce((s,item)=>s+item.amount,0),0); return manual+towerIncome; }
function calculateUpgradeCostDelta(towerId,fromUpgrade="000",toUpgrade="000"){ const tower=getTower(towerId); if(!tower||fromUpgrade==="PARAGON"||toUpgrade==="PARAGON")return 0; const from=upgradeNums(fromUpgrade), to=upgradeNums(toUpgrade); let total=0; for(let path=0;path<3;path++){ for(let tier=from[path]+1;tier<=to[path];tier++){ const code=[0,0,0]; code[path]=tier; total+=priceWithDifficulty(tower.upgradeCosts?.[code.join("")]||0); } } return total; }
function getBuffsForMonkey(id){return state.buffs.filter(b=>b.targetMonkeyId===id)}
function compareEvents(a,b){ if(a.tick!==b.tick)return a.tick-b.tick; const order={"pop-income":0,"round-pop-income":0,"tower-income":0,"place":1,"place-hero":1,"place-geraldo-item":1,"snapshot":2,"upgrade":3,"hero-level":2,"bank-deposit":3,"bank-collect":4,"ability":5,"absorb":6,"paragon":7,"sell":9}; return (order[a.type]??9)-(order[b.type]??9)||a.sortOrder-b.sortOrder; }
function isSpecialEvent(e){return ["bank-collect","bank-deposit","absorb","paragon","ability","hero-level","pop-income","tower-income","round-pop-income"].includes(e.type)}
function getTower(id){return window.BTD6_TOWERS.find(t=>t.id===id)} function getHero(id){return window.BTD6_HEROES.find(h=>h.id===id)} function getSelectedHero(){return getHero(state.settings.selectedHero)} function getGeraldoItem(id){return window.BTD6_GERALDO_ITEMS.find(i=>i.id===id)}
function getInstanceMeta(inst,round=state.endRound){ if(inst.kind==="hero")return {iconKey:getHero(inst.heroId).iconKey,typeLabel:"Hero",category:"hero",absorbedVisible:false}; if(inst.kind==="geraldo-item")return {iconKey:getGeraldoItem(inst.itemId).iconKey,typeLabel:"Geraldo Item",category:"hero",absorbedVisible:false}; if(inst.kind==="paragon")return {iconKey:"paragon",typeLabel:"Paragon",category:"hero",absorbedVisible:false}; const t=getTower(inst.towerId); const visible=!!inst.absorbedBy && isExistingDragDisabled(inst,round); const absorbEvent=inst.absorbedBy?state.events.find(e=>e.id===inst.absorbedBy):null; const released=absorbEvent&&state.events.some(e=>e.monkeyId===absorbEvent.monkeyId&&e.type==="sell"&&e.round<=round); const absorbedText=inst.absorbedBy&&!released?`${inst.absorbedKind==="pending-village"?"pending absorb":"absorbed "+inst.absorbedKind}`:""; return {iconKey:t.iconKey,typeLabel:t.category,category:t.category,absorbedVisible:visible,absorbedText}; }
function getHelperMeta(ev){ if(ev.type==="pop-income"||ev.type==="tower-income"||ev.type==="round-pop-income")return {iconKey:"popIncome",category:"helper"}; return {iconKey:"item",category:"helper"}; }
function formatMoney(v){return `$${Math.round(Number(v||0)).toLocaleString()}`}
function makeId(prefix,n){return `${prefix}-${n}`} function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
function showToast(msg){ el.toast.textContent=msg; el.toast.classList.remove("hidden"); clearTimeout(showToast.t); showToast.t=setTimeout(()=>el.toast.classList.add("hidden"),2300); }

const tutorialSteps=[
  {target:"header",title:"OptimalBtd6",text:"This top bar is where future calculators can live. Farming Planner is the active one right now."},
  {target:"left-panel",title:"Planner Setup",text:"Set the event type, goal, round start, cash, map difficulty, players, hero, and tower limits here."},
  {target:"right-panel",title:"Available / Existing / Rules",text:"Drag available cards into rounds, reuse existing monkeys for upgrades, and limit tower paths in Rules."},
  {target:"round-map",title:"Round Map",text:"Every important choice becomes a tick-sorted action: placements, upgrades, sells, bank actions, absorbs, abilities, paragons, and pop-income movement."},
  {target:"inspector",title:"Selected Action",text:"Click an action to edit its tick, upgrade tiers, special sub-actions, buffs, or delete/sell it."}
];
function startTutorial(){ state.tutorialIndex=0; showTutorialStep(); }
function showTutorialStep(){ const step=tutorialSteps[state.tutorialIndex]; if(!step){endTutorial();return;} const target=document.querySelector(`[data-tutorial='${step.target}']`); el.tutorialOverlay.classList.remove("hidden"); if(target){ target.scrollIntoView({block:"nearest",inline:"nearest"}); requestAnimationFrame(()=>positionTutorialHighlight(target)); } else { positionTutorialHighlight(null); } el.tutorialTitle.textContent=step.title; el.tutorialText.textContent=step.text; el.tutorialNext.textContent=state.tutorialIndex===tutorialSteps.length-1?"Finish":"Next"; }
function positionTutorialHighlight(target){ if(!el.tutorialHighlight)return; if(!target){ el.tutorialHighlight.style.display="none"; return; } const r=target.getBoundingClientRect(); el.tutorialHighlight.style.display="block"; el.tutorialHighlight.style.left=`${Math.max(8,r.left-6)}px`; el.tutorialHighlight.style.top=`${Math.max(8,r.top-6)}px`; el.tutorialHighlight.style.width=`${Math.min(window.innerWidth-16,r.width+12)}px`; el.tutorialHighlight.style.height=`${Math.min(window.innerHeight-16,r.height+12)}px`; }
function nextTutorialStep(){ state.tutorialIndex++; showTutorialStep(); }
function endTutorial(){ positionTutorialHighlight(null); el.tutorialOverlay.classList.add("hidden"); }

init();
